-------------------------------------------------------
-- This file has been generated by Dungeon Editor 1.3.7
-------------------------------------------------------
--
-- SKELETON WARRIOR - AXE
--
-- Legend of Grimrock Custom Monster
-- created by Leki 
-- April, 7th, 2013
-- v 1.0
-------------------------------------------------------
-- Original mesh and texture source: LoG assets pack
-- Source was modified (new weapon, skin and animations) by Leki
-- Weapon texture - Corrupt Great Axe by Asteroth 
-- GMT v5.0.2 by JohnWordsworth, CW Tools by Wallasaurus
--
-- To install custom monster please paste to the init.lua next line (without first two characters)
--
-- import "mod_assets/plugins/skeleton_warrior_axe/skeleton_warrior_axe.lua" -- custom monster Skeleton Warrior - Axe created by Leki
--
-- Please report bugs here: http://www.grimrock.net/forum/viewtopic.php?f=14&t=5230#p56904
--
-- Legend of Grimrock: http://www.grimrock.net/ 
-------------------------------------------------------
-- monster definition
-------------------------------------------------------

defineObject{
	name = "leki_skeleton_warrior_axe",
	class = "Monster",
	model = "mod_assets/plugins/skeleton_warrior_axe/models/skeleton_warrior_axe.fbx",
	meshName = "skeleton_warrior_mesh",
	animations = {
		idle = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_idle.fbx",
		moveForward = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_walk.fbx",
		turnLeft = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_turn_left.fbx",
		turnRight = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_turn_right.fbx",
		attack = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_attack.fbx",
		attackBack = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_attack.fbx",
		getHitFrontLeft = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_left.fbx",
		getHitFrontRight = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_right.fbx",
		getHitBack = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_back.fbx",
		getHitLeft = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_left.fbx",
		getHitRight = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_right.fbx",
		fall = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_hit_left.fbx",
	},
	moveSound = "skeleton_walk",
	footstepSound = "skeleton_footstep",
	attackSound = "skeleton_attack",
	hitSound = "skeleton_hit",
	dieSound = "skeleton_die",
	hitEffect = "hit_dust",
	capsuleHeight = 0.7,
	capsuleRadius = 0.25,
	collisionRadius = 0.6,
	health = 120,
	sight = 4,
	attackPower = 9,
	accuracy = 10,
	protection = 5,
	immunities = { "poison" },
	movementCoolDown = 2,
	noRecoilInterval = { 0.25, 0.5 },
	exp = 90,
	lootDrop = { 100, "rusted_great_axe" },
	healthIncrement = 15,
	attackPowerIncrement = 5,
	protectionIncrement = 1,
	brain = "Melee",
}

defineObject{
	name = "leki_skeleton_warrior_axe_patrol_4",
	class = "MonsterGroup",
	monsterType = "leki_skeleton_warrior_axe",
	count = 4,
}

defineObject{
	name = "leki_skeleton_warrior_axe_patrol_2",
	class = "MonsterGroup",
	monsterType = "leki_skeleton_warrior_axe",
	count = 2,
}

-------------------------------------------------------
-- animation events
-------------------------------------------------------
defineAnimationEvent{
	animation = "mod_assets/plugins/skeleton_warrior_axe/animations/skeleton_warrior_axe_attack.fbx",
	event = "attack",
	frame = 13,
}

-------------------------------------------------------
-- weapons
-------------------------------------------------------
defineObject{
	name = "rusted_great_axe",
	class = "Item",
	uiName = "Rusted Great Axe",
	model = "mod_assets/plugins/skeleton_warrior_axe/models/rusted_great_axe.fbx",
	description = "Rusted but still deadly piece of stell.",
	skill = "axes",
	requiredLevel = 2,
	gfxIndex = 11,
	attackPower = 8,
	accuracy = 0,
	coolDownTime = 4.6,
	attackMethod = "meleeAttack",
	attackSwipe = "horizontal",
	attackSound = "swipe_heavy",
	impactSound = "impact_blade",
	weight = 6.0,
}

-------------------------------------------------------
-- materials
-------------------------------------------------------
defineMaterial{
	name = "rusted_great_axe",
	diffuseMap = "mod_assets/plugins/skeleton_warrior_axe/textures/corrupt_great_axe_dif.tga",
	specularMap = "mod_assets/plugins/skeleton_warrior_axe/textures/corrupt_great_axe_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 35,
	depthBias = 0,
}





