-- This file has been generated by Dungeon Editor beta-1.2.6

-- import standard assets
import "assets/scripts/standard_assets.lua"

-- import custom assets
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/monsters_EobConverter.lua"
import "mod_assets/scripts/monsters_EobConverter_workaround.lua"
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/items_EobConverter.lua"
import "mod_assets/scripts/framework.lua"
import "mod_assets/scripts/framework/spells.lua"
import "mod_assets/scripts/framework/items.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/objects_EobConverter.lua"
import "mod_assets/scripts/wall_sets.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"
import "mod_assets/scripts/particles.lua"

import "mod_assets/scripts/notes.lua"