-- This file has been generated by Dungeon Editor beta-1.2.6

-- import standard assets
import "assets/scripts/standard_assets.lua"

import "mod_assets/framework/framework.lua"
fw_setShowWarnings(false) -- don't show warning about script entites found from dungeon
fw_loadModule('fw_magic')
fw_loadModule('add_spells')
fw_loadModule('illusion_walls')
fw_loadModule('t')
fw_loadModule('events')


import "mod_assets/grimwidgets/grimwidgets.lua"

-- assets must be imported after the framework, otherwise hooks don't work

-- import assets generated by EobConverter
-- They should be included before normal definitions, as they include
-- some dummy definitions. They can be overwritten later, using
-- monsters.lua, items.lua and objects.lua. Please DO NOT edit
-- EobConverter files as they will be replaced the next time they
-- are regenerated.
import "mod_assets/scripts/monsters_EobConverter.lua"
import "mod_assets/scripts/items_EobConverter.lua"
import "mod_assets/scripts/objects_EobConverter.lua"

-- Custom skeleton+axe by Leki
import "mod_assets/plugins/skeleton_warrior_axe/skeleton_warrior_axe.lua"

-- import custom assets
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/wall_sets.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"
import "mod_assets/scripts/particles.lua"

import "mod_assets/scripts/notes.lua"
