-- This file has been generated by EobConverter v0.9.9

---------------
--- Level 0 ---
---------------

cloneObject {
	name = "eob_axe_u",  -- Mouse Pointer
	baseObject = "hand_axe",
	uiName = "Mouse Pointer",
}

cloneObject {
	name = "eob_axe",
	baseObject = "hand_axe",
	uiName = "Mouse Pointer",
}

cloneObject {
	name = "eob_leather_armor_u",  -- Leather armor
	baseObject = "leather_brigandine",
	uiName = "Leather armor",
	slot = "Torso",
	protection = 4,
}

cloneObject {
	name = "eob_leather_armor",
	baseObject = "leather_brigandine",
	uiName = "Leather armor",
	slot = "Torso",
	protection = 4,
}

cloneObject {
	name = "eob_robe_u",  -- Robe
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_robe",
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_staff_u",  -- Staff
	baseObject = "whitewood_wand",
	uiName = "Staff",
}

cloneObject {
	name = "eob_staff",
	baseObject = "whitewood_wand",
	uiName = "Staff",
}

cloneObject {
	name = "eob_dagger_u",  -- Dagger
	baseObject = "dagger",
	uiName = "Dagger",
}

cloneObject {
	name = "eob_dagger",
	baseObject = "dagger",
	uiName = "Dagger",
}

cloneObject {
	name = "eob_short_sword_u",  -- Short sword
	baseObject = "cutlass",
	uiName = "Short sword",
}

cloneObject {
	name = "eob_short_sword",
	baseObject = "cutlass",
	uiName = "Short sword",
}

cloneObject {
	name = "eob_lock_picks_u",  -- Lock picks
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_lock_picks",
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_spell_book_u",  -- Spellbook
	baseObject = "tome_wisdom",
	uiName = "Spellbook",
}

cloneObject {
	name = "eob_spell_book",
	baseObject = "tome_wisdom",
	uiName = "Spellbook",
}

cloneObject {
	name = "eob_holy_symbol_u",  -- Cleric Holy symbol
	baseObject = "golden_chalice",
	uiName = "Cleric Holy symbol",
}

cloneObject {
	name = "eob_holy_symbol",
	baseObject = "golden_chalice",
	uiName = "Cleric Holy symbol",
}

cloneObject {
	name = "eob_leather_boots_u",  -- Leather boots
	baseObject = "leather_boots",
	uiName = "Leather boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Leather boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_key_jeweled_u",  -- Jeweled Key
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_key_jeweled",
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_potion_giant_strength_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_giant_strength",
	baseObject = "potion_healing",
	uiName = "Potion of Giant Strength",
}

cloneObject {
	name = "eob_gem_blue_u",  -- Gem
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_gem_blue",
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_key_skull_u",  -- Skull Key
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_key_skull",
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_wand_cone_of_cold_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_cone_of_cold_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Cone of Cold",
	charges = 10,
}

cloneObject {
	name = "eob_scroll_text4_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text4",
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_ring2_sustenance_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_sustenance",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Sustenance",
}

cloneObject {
	name = "eob_ring2_feather_fall_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_feather_fall",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Feather Fall",
}

cloneObject {
	name = "eob_ring_protection2_u",  -- Ring
	baseObject = "hardstone_bracelet",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring_protection2",
	baseObject = "hardstone_bracelet",
	uiName = "Ring of Protection +2",
}

cloneObject {
	name = "eob_dart_plus5_u",  -- Adamantite Dart
	baseObject = "shuriken",
	uiName = "Adamantite Dart",
}

cloneObject {
	name = "eob_dart_plus5",
	baseObject = "shuriken",
	uiName = "Adamantite Dart +5",
}

cloneObject {
	name = "eob_scroll_text1_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text1",
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text2_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text2",
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text3_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_scroll_text3",
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_rations_iron_double_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron_double",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_holy_symbol_u",  -- Paladin Holy Symbol
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}

cloneObject {
	name = "eob_holy_symbol",
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}

cloneObject {
	name = "eob_wand_slivias_17_u",  -- Wand of Slivias
	baseObject = "whitewood_wand",
	uiName = "Wand of Slivias",
	charges = 17,
}

cloneObject {
	name = "eob_wand_slivias_17",
	baseObject = "whitewood_wand",
	uiName = "Wand of Slivias",
	charges = 17,
}

cloneObject {
	name = "eob_bones_not_used_in_dungeon_u",  -- Dwarf Bones
	baseObject = "remains_of_toorum",
	uiName = "Dwarf Bones",
}

cloneObject {
	name = "eob_bones_not_used_in_dungeon",
	baseObject = "remains_of_toorum",
	uiName = "Dwarf Bones",
}

cloneObject {
	name = "eob_key_u",  -- Key
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_key",
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_scroll_not_used_in_dungeon_u",  -- Commission and Letter of Marque
	baseObject = "scroll",
	uiName = "Commission and Letter of Marque",
}

cloneObject {
	name = "eob_scroll_not_used_in_dungeon",
	baseObject = "scroll",
	uiName = "Commission and Letter of Marque",
}

cloneObject {
	name = "eob_axe_u",  -- Axe
	baseObject = "hand_axe",
	uiName = "Axe",
}

cloneObject {
	name = "eob_axe",
	baseObject = "hand_axe",
	uiName = "Axe",
}

cloneObject {
	name = "eob_dart_u",  -- Dart
	baseObject = "shuriken",
	uiName = "Dart",
}

cloneObject {
	name = "eob_dart",
	baseObject = "shuriken",
	uiName = "Dart",
}

cloneObject {
	name = "eob_dart_plus4_u",  -- Adamantite Dart
	baseObject = "shuriken",
	uiName = "Adamantite Dart",
}

cloneObject {
	name = "eob_dart_plus4",
	baseObject = "shuriken",
	uiName = "Adamantite Dart +4",
}

cloneObject {
	name = "eob_halberd_u",  -- Halberd
	baseObject = "legionary_spear",
	uiName = "Halberd",
}

cloneObject {
	name = "eob_halberd",
	baseObject = "legionary_spear",
	uiName = "Halberd",
}

cloneObject {
	name = "eob_chain_mail_u",  -- Chainmail
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_chain_mail",
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_dwarven_helmet_u",  -- Helmet
	baseObject = "full_helmet",
	uiName = "Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_dwarven_helmet",
	baseObject = "full_helmet",
	uiName = "Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_dwarven_helmet_u",  -- Dwarf Helmet
	baseObject = "full_helmet",
	uiName = "Dwarf Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_dwarven_helmet",
	baseObject = "full_helmet",
	uiName = "Dwarf Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_key_silver_u",  -- Silver Key
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_key_silver",
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_long_sword_sharp_u",  -- Adamantite Long Sword
	baseObject = "long_sword",
	uiName = "Adamantite Long Sword",
}

cloneObject {
	name = "eob_long_sword_sharp",
	baseObject = "long_sword",
	uiName = "Sharp Adamantite Long Sword",
}

cloneObject {
	name = "eob_mace_u",  -- Mace
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject {
	name = "eob_mace",
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject {
	name = "eob_long_sword_cursed2_u",  -- Longsword
	baseObject = "long_sword",
	uiName = "Longsword",
}

cloneObject {
	name = "eob_long_sword_cursed2",
	baseObject = "long_sword",
	uiName = "Unlucky Longsword",
}

cloneObject {
	name = "eob_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
}

cloneObject {
	name = "eob_dagger_guinsoo_u",  -- 'Guinsoo'
	baseObject = "dagger",
	uiName = "'Guinsoo'",
}

cloneObject {
	name = "eob_dagger_guinsoo",
	baseObject = "dagger",
	uiName = "'Guinsoo'",
}

cloneObject {
	name = "eob_gem_red_u",  -- Gem
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_gem_red",
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_orb_of_power_u",  -- Orb of Power
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_orb_of_power",
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_rock_glowing_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_glowing",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_rations_u",  -- Rations
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_rations",
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_robe_u",  -- Fancy Robe
	baseObject = "peasant_tunic",
	uiName = "Fancy Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_robe",
	baseObject = "peasant_tunic",
	uiName = "Fancy Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_glowing_u",  -- Igneous Rock
	baseObject = "rock",
	uiName = "Igneous Rock",
}

cloneObject {
	name = "eob_rock_glowing",
	baseObject = "rock",
	uiName = "Igneous Rock",
}

cloneObject {
	name = "eob_mage_scroll_detect_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_detect_magic",
	baseObject = "scroll",
	uiName = "Scroll of Detect Magic",
}

cloneObject {
	name = "eob_spear_u",  -- Spear
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_spear",
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_stone_medallion_u",  -- Stone Medallion
	baseObject = "rock",
	uiName = "Stone Medallion",
}

cloneObject {
	name = "eob_stone_medallion",
	baseObject = "rock",
	uiName = "Stone Medallion",
}

---------------
--- Level 1 ---
---------------

cloneObject {
	name = "eob_rations_u",  -- Rations
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_rations",
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_bones_halfling_tod_u",  -- Halfling Bones
	baseObject = "remains_of_toorum",
	uiName = "Halfling Bones",
}

cloneObject {
	name = "eob_bones_halfling_tod",
	baseObject = "remains_of_toorum",
	uiName = "Halfling Bones",
}

cloneObject {
	name = "eob_lock_picks_u",  -- Lock picks
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_lock_picks",
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_dart_plus2_u",  -- Dart
	baseObject = "shuriken",
	uiName = "Dart",
}

cloneObject {
	name = "eob_dart_plus2",
	baseObject = "shuriken",
	uiName = "Dart +2",
}

cloneObject {
	name = "eob_cleric_scroll_bless_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_bless",
	baseObject = "scroll",
	uiName = "Scroll of Bless",
}

cloneObject {
	name = "eob_mage_scroll_armor_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_armor",
	baseObject = "scroll",
	uiName = "Scroll of Armor",
}

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_shield_u",  -- Shield
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

---------------
--- Level 2 ---
---------------

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_rations_u",  -- Rations
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_rations",
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_leather_boots_u",  -- Leather boots
	baseObject = "leather_boots",
	uiName = "Leather boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Leather boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
}

cloneObject {
	name = "eob_key_silver_u",  -- Silver Key
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_key_silver",
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_potion_giant_strength_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_giant_strength",
	baseObject = "potion_healing",
	uiName = "Potion of Giant Strength",
}

cloneObject {
	name = "eob_key_gold_u",  -- Gold Key
	baseObject = "brass_key",
	uiName = "Gold Key",
}

cloneObject {
	name = "eob_key_gold",
	baseObject = "brass_key",
	uiName = "Gold Key",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_bow_u",  -- Bow
	baseObject = "short_bow",
	uiName = "Bow",
}

cloneObject {
	name = "eob_bow",
	baseObject = "short_bow",
	uiName = "Bow",
}

cloneObject {
	name = "eob_stone_dagger_u",  -- Stone dagger
	baseObject = "rock",
	uiName = "Stone dagger",
}

cloneObject {
	name = "eob_stone_dagger",
	baseObject = "rock",
	uiName = "Stone dagger",
}

cloneObject {
	name = "eob_mage_scroll_invisibility_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_invisibility",
	baseObject = "scroll",
	uiName = "Scroll of Invisibility",
}

cloneObject {
	name = "eob_mage_scroll_shield_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_shield",
	baseObject = "scroll",
	uiName = "Scroll of Shield",
}

cloneObject {
	name = "eob_sling_u",  -- Sling
	baseObject = "sling",
	uiName = "Sling",
}

cloneObject {
	name = "eob_sling",
	baseObject = "sling",
	uiName = "Sling",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_potion_vitality_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_vitality",
	baseObject = "potion_healing",
	uiName = "Potion of Vitality",
}

---------------
--- Level 3 ---
---------------

cloneObject {
	name = "eob_gem_blue_u",  -- Gem
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_gem_blue",
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_chain_mail_u",  -- Chainmail
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_chain_mail",
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_shield_u",  -- Shield
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_key_silver_u",  -- Silver Key
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_key_silver",
	baseObject = "brass_key",
	uiName = "Silver Key",
}

cloneObject {
	name = "eob_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_mage_scroll_detect_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_detect_magic",
	baseObject = "scroll",
	uiName = "Scroll of Detect Magic",
}

cloneObject {
	name = "eob_dagger_backstabber_u",  -- 'Backstabber'
	baseObject = "dagger",
	uiName = "'Backstabber'",
}

cloneObject {
	name = "eob_dagger_backstabber",
	baseObject = "dagger",
	uiName = "'Backstabber' of +3",
}

cloneObject {
	name = "eob_rations_u",  -- Rations
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_rations",
	baseObject = "pitroot_bread",
	uiName = "Rations",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade",
	baseObject = "scroll",
	uiName = "Scroll of Flame Blade",
}

cloneObject {
	name = "eob_mage_scroll_fireball_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_fireball",
	baseObject = "scroll",
	uiName = "Scroll of Fireball",
}

cloneObject {
	name = "eob_cleric_scroll_cause_light_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cause_light_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cause Light Wounds",
}

cloneObject {
	name = "eob_gem_red_u",  -- Gem
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_gem_red",
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_long_sword_u",  -- Long Sword
	baseObject = "long_sword",
	uiName = "Long Sword",
}

cloneObject {
	name = "eob_long_sword",
	baseObject = "long_sword",
	uiName = "Long Sword",
}

cloneObject {
	name = "eob_wand_magic_missile_3_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 3,
}

cloneObject {
	name = "eob_wand_magic_missile_3",
	baseObject = "whitewood_wand",
	uiName = "Wand of Magic Missile",
	charges = 3,
}

cloneObject {
	name = "eob_bones_human_anya_u",  -- Human Bones
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_bones_human_anya",
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_leather_armor_u",  -- Leather armor
	baseObject = "leather_brigandine",
	uiName = "Leather armor",
	slot = "Torso",
	protection = 4,
}

cloneObject {
	name = "eob_leather_armor",
	baseObject = "leather_brigandine",
	uiName = "Leather armor",
	slot = "Torso",
	protection = 4,
}

cloneObject {
	name = "eob_spear_u",  -- Spear
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_spear",
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_potion_speed_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_speed",
	baseObject = "potion_healing",
	uiName = "Potion of Speed",
}

---------------
--- Level 4 ---
---------------

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_mace_u",  -- Mace
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject {
	name = "eob_mace",
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject {
	name = "eob_ring_protection3_u",  -- Ring
	baseObject = "hardstone_bracelet",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring_protection3",
	baseObject = "hardstone_bracelet",
	uiName = "Ring of Protection +3",
}

cloneObject {
	name = "eob_key_dwarven_u",  -- Dwarven Key
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_key_dwarven",
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_ring2_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2",
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
}

cloneObject {
	name = "eob_potion_cure_poison_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_cure_poison",
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_medallion_of_adornment_u",  -- Medallion
	baseObject = "spirit_mirror_pendant",
	uiName = "Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_of_adornment",
	baseObject = "spirit_mirror_pendant",
	uiName = "Medallion of Adornment",
	slot = "Neck",
}

cloneObject {
	name = "eob_robe_u",  -- Robe
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_robe",
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_axe_drow_cleaver_u",  -- 'Drow Cleaver'
	baseObject = "hand_axe",
	uiName = "'Drow Cleaver'",
}

cloneObject {
	name = "eob_axe_drow_cleaver",
	baseObject = "hand_axe",
	uiName = "'Drow Cleaver'",
}

cloneObject {
	name = "eob_stone_scepter_u",  -- Stone Scepter
	baseObject = "rock",
	uiName = "Stone Scepter",
}

cloneObject {
	name = "eob_stone_scepter",
	baseObject = "rock",
	uiName = "Stone Scepter",
}

cloneObject {
	name = "eob_mage_scroll_flame_arrow_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_flame_arrow",
	baseObject = "scroll",
	uiName = "Scroll of Flame Arrow",
}

cloneObject {
	name = "eob_cleric_scroll_slow_poison_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_slow_poison",
	baseObject = "scroll",
	uiName = "Scroll of Slow Poison",
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_dwarven_helmet_u",  -- Dwarven Helmet
	baseObject = "full_helmet",
	uiName = "Dwarven Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_dwarven_helmet",
	baseObject = "full_helmet",
	uiName = "Dwarven Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_shield_u",  -- Dwarven Shield
	baseObject = "round_shield",
	uiName = "Dwarven Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Dwarven Shield",
	protection = 2,
}

cloneObject {
	name = "eob_potion_cure_poison_u",  -- Cure Poison Potion
	baseObject = "potion_healing",
	uiName = "Cure Poison Potion",
}

cloneObject {
	name = "eob_potion_cure_poison",
	baseObject = "potion_healing",
	uiName = "Cure Poison Potion",
}

---------------
--- Level 5 ---
---------------

cloneObject {
	name = "eob_wand_cone_of_cold_2_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 2,
}

cloneObject {
	name = "eob_wand_cone_of_cold_2",
	baseObject = "whitewood_wand",
	uiName = "Wand of Cone of Cold",
	charges = 2,
}

cloneObject {
	name = "eob_cleric_scroll_hold_person_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_hold_person",
	baseObject = "scroll",
	uiName = "Scroll of Hold Person",
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_spear_u",  -- Spear
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_spear",
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_stone_necklace_u",  -- Stone Necklace
	baseObject = "rock",
	uiName = "Stone Necklace",
}

cloneObject {
	name = "eob_stone_necklace",
	baseObject = "rock",
	uiName = "Stone Necklace",
}

cloneObject {
	name = "eob_cleric_scroll_aid_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_aid",
	baseObject = "scroll",
	uiName = "Scroll of Aid",
}

cloneObject {
	name = "eob_mage_scroll_haste_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_haste",
	baseObject = "scroll",
	uiName = "Scroll of Haste",
}

cloneObject {
	name = "eob_cleric_scroll_detect_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_detect_magic",
	baseObject = "scroll",
	uiName = "Scroll of Detect Magic",
}

cloneObject {
	name = "eob_long_sword_u",  -- Long Sword
	baseObject = "long_sword",
	uiName = "Long Sword",
}

cloneObject {
	name = "eob_long_sword",
	baseObject = "long_sword",
	uiName = "Long Sword",
}

cloneObject {
	name = "eob_potion_poison_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_poison",
	baseObject = "potion_healing",
	uiName = "Potion of Poison",
}

cloneObject {
	name = "eob_mage_scroll_dispel_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_dispel_magic",
	baseObject = "scroll",
	uiName = "Scroll of Dispel Magic",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_plate_mail_u",  -- Plate Mail
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_plate_mail",
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_key_dwarven_u",  -- Dwarven Key
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_key_dwarven",
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_scale_mail_u",  -- Scale Mail
	baseObject = "ring_mail",
	uiName = "Scale Mail",
	slot = "Torso",
	protection = 8,
}

cloneObject {
	name = "eob_scale_mail",
	baseObject = "ring_mail",
	uiName = "Scale Mail",
	slot = "Torso",
	protection = 8,
}

cloneObject {
	name = "eob_axe_cursed3_u",  -- Axe
	baseObject = "hand_axe",
	uiName = "Axe",
}

cloneObject {
	name = "eob_axe_cursed3",
	baseObject = "hand_axe",
	uiName = "Axe Cursed -3",
}

cloneObject {
	name = "eob_sling_cursed3_u",  -- Sling
	baseObject = "sling",
	uiName = "Sling",
}

cloneObject {
	name = "eob_sling_cursed3",
	baseObject = "sling",
	uiName = "Sling Cursed -3",
}

cloneObject {
	name = "eob_key_u",  -- Key
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_key",
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_ring2_feather_fall_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_feather_fall",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Feather Fall",
}

cloneObject {
	name = "eob_mage_scroll_invisibility 10'_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_invisibility 10'",
	baseObject = "scroll",
	uiName = "Scroll of Invisibility 10'",
}

cloneObject {
	name = "eob_cleric_scroll_prayer_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_prayer",
	baseObject = "scroll",
	uiName = "Scroll of Prayer",
}

cloneObject {
	name = "eob_leather_boots_u",  -- Boots
	baseObject = "leather_boots",
	uiName = "Boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Boots",
	slot = "Feet",
}

---------------
--- Level 6 ---
---------------

cloneObject {
	name = "eob_egg_20_u",  -- Kenku Egg
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_20",
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_30_u",  -- Kenku Egg
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_30",
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_40_u",  -- Kenku Egg
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_40",
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_egg_10_u",  -- Kenku Egg
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
	stackable = false,
}

cloneObject {
	name = "eob_egg_10",
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
}

cloneObject {
	name = "eob_key_dwarven_u",  -- Dwarven Key
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_key_dwarven",
	baseObject = "brass_key",
	uiName = "Dwarven Key",
}

cloneObject {
	name = "eob_mage_scroll_hold_person_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_hold_person",
	baseObject = "scroll",
	uiName = "Scroll of Hold Person",
}

cloneObject {
	name = "eob_stone_ring_u",  -- Stone Ring
	baseObject = "rock",
	uiName = "Stone Ring",
}

cloneObject {
	name = "eob_stone_ring",
	baseObject = "rock",
	uiName = "Stone Ring",
}

cloneObject {
	name = "eob_rock_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_cleric_scroll_dispel_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_dispel_magic",
	baseObject = "scroll",
	uiName = "Scroll of Dispel Magic",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Serious Wounds",
}

cloneObject {
	name = "eob_key_u",  -- Key
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_key",
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_shield_dwarven_u",  -- Dwarven Shield
	baseObject = "round_shield",
	uiName = "Dwarven Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield_dwarven",
	baseObject = "round_shield",
	uiName = "Dwarven Dwarven Shield",
	protection = 2,
}

cloneObject {
	name = "eob_mace_plus3_u",  -- Mace
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject {
	name = "eob_mace_plus3",
	baseObject = "knoffer",
	uiName = "Mace of +3",
}

cloneObject {
	name = "eob_bracers_u",  -- Bracers
	baseObject = "bracelet_tirin",
	uiName = "Bracers",
	slot = "Bracers",
}

cloneObject {
	name = "eob_bracers",
	baseObject = "bracelet_tirin",
	uiName = "Bracers",
	slot = "Bracers",
}

cloneObject {
	name = "eob_wand_magic_missile_20_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 20,
}

cloneObject {
	name = "eob_wand_magic_missile_20",
	baseObject = "whitewood_wand",
	uiName = "Wand of Magic Missile",
	charges = 20,
}

cloneObject {
	name = "eob_ring2_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2",
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade",
	baseObject = "scroll",
	uiName = "Scroll of Flame Blade",
}

cloneObject {
	name = "eob_halberd_chieftain_u",  -- Chieftain Halberd
	baseObject = "legionary_spear",
	uiName = "Chieftain Halberd",
}

cloneObject {
	name = "eob_halberd_chieftain",
	baseObject = "legionary_spear",
	uiName = "Chieftain Chieftain Halberd",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_dart_plus4_u",  -- Adamantite Dart
	baseObject = "shuriken",
	uiName = "Adamantite Dart",
}

cloneObject {
	name = "eob_dart_plus4",
	baseObject = "shuriken",
	uiName = "Adamantite Dart +4",
}

cloneObject {
	name = "eob_dagger_u",  -- Dagger
	baseObject = "dagger",
	uiName = "Dagger",
}

cloneObject {
	name = "eob_dagger",
	baseObject = "dagger",
	uiName = "Dagger",
}

---------------
--- Level 7 ---
---------------

cloneObject {
	name = "eob_mage_scroll_fireball_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_fireball",
	baseObject = "scroll",
	uiName = "Scroll of Fireball",
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_medallion_of_adornment_u",  -- Necklace
	baseObject = "spirit_mirror_pendant",
	uiName = "Necklace",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_of_adornment",
	baseObject = "spirit_mirror_pendant",
	uiName = "Necklace of Adornment",
	slot = "Neck",
}

cloneObject {
	name = "eob_cleric_scroll_bless_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_bless",
	baseObject = "scroll",
	uiName = "Scroll of Bless",
}

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil10_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil10",
	baseObject = "scroll",
	uiName = "Scroll of Protect-Evil 10'",
}

cloneObject {
	name = "eob_cleric_scroll_remove_paralysis_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_remove_paralysis",
	baseObject = "scroll",
	uiName = "Scroll of Remove Paralysis",
}

cloneObject {
	name = "eob_cleric_scroll_slow_poison_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_slow_poison",
	baseObject = "scroll",
	uiName = "Scroll of Slow Poison",
}

cloneObject {
	name = "eob_cleric_scroll_create_food_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_create_food",
	baseObject = "scroll",
	uiName = "Scroll of Create Food",
}

cloneObject {
	name = "eob_key_u",  -- Key
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_key",
	baseObject = "brass_key",
	uiName = "Key",
}

cloneObject {
	name = "eob_medallion_luck_stone_u",  -- Medallion
	baseObject = "frostbite_necklace",
	uiName = "Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_luck_stone",
	baseObject = "frostbite_necklace",
	uiName = "Luck Stone Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_ring_protection2_u",  -- Ring
	baseObject = "hardstone_bracelet",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring_protection2",
	baseObject = "hardstone_bracelet",
	uiName = "Ring of Protection +2",
}

cloneObject {
	name = "eob_short_sword_slicer_u",  -- 'Slicer'
	baseObject = "cutlass",
	uiName = "'Slicer'",
}

cloneObject {
	name = "eob_short_sword_slicer",
	baseObject = "cutlass",
	uiName = "'Slicer'",
}

cloneObject {
	name = "eob_bracers_defense3_u",  -- Bracers
	baseObject = "bracelet_tirin",
	uiName = "Bracers",
	slot = "Bracers",
}

cloneObject {
	name = "eob_bracers_defense3",
	baseObject = "bracelet_tirin",
	uiName = "Elven Bracers of Defense",
	slot = "Bracers",
}

cloneObject {
	name = "eob_ring2_wizardry_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_wizardry",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Wizardry",
}

cloneObject {
	name = "eob_mage_scroll_fear_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_fear",
	baseObject = "scroll",
	uiName = "Scroll of Fear",
}

cloneObject {
	name = "eob_key_jeweled_u",  -- Jeweled Key
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_key_jeweled",
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_banded_armor_u",  -- Banded Armor
	baseObject = "ring_mail",
	uiName = "Banded Armor",
	slot = "Torso",
	protection = 12,
}

cloneObject {
	name = "eob_banded_armor",
	baseObject = "ring_mail",
	uiName = "Banded Armor",
	slot = "Torso",
	protection = 12,
}

cloneObject {
	name = "eob_key_drow_u",  -- Drow Key
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_key_drow",
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_mage_scroll_lightning_bolt_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_lightning_bolt",
	baseObject = "scroll",
	uiName = "Scroll of Lightning Bolt",
}

cloneObject {
	name = "eob_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
}

cloneObject {
	name = "eob_cleric_scroll_cure_light_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_light_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Light Wounds",
}

cloneObject {
	name = "eob_key_ruby_u",  -- Ruby Key
	baseObject = "brass_key",
	uiName = "Ruby Key",
}

cloneObject {
	name = "eob_key_ruby",
	baseObject = "brass_key",
	uiName = "Ruby Key",
}

cloneObject {
	name = "eob_rock_glowing_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_glowing",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_wand_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
}

cloneObject {
	name = "eob_wand",
	baseObject = "whitewood_wand",
	uiName = "Wand",
}

cloneObject {
	name = "eob_shield_u",  -- Shield
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_bones_human_ileria_u",  -- Human Bones
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_bones_human_ileria",
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_holy_symbol_u",  -- Holy Symbol
	baseObject = "golden_chalice",
	uiName = "Holy Symbol",
}

cloneObject {
	name = "eob_holy_symbol",
	baseObject = "golden_chalice",
	uiName = "Holy Symbol",
}

---------------
--- Level 8 ---
---------------

cloneObject {
	name = "eob_cleric_scroll_prayer_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_prayer",
	baseObject = "scroll",
	uiName = "Scroll of Prayer",
}

cloneObject {
	name = "eob_cleric_scroll_neutral_poison_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_neutral_poison",
	baseObject = "scroll",
	uiName = "Scroll of Neutral-Poison",
}

cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Critical Wounds",
}

cloneObject {
	name = "eob_medallion_of_adornment_u",  -- Medallion
	baseObject = "spirit_mirror_pendant",
	uiName = "Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_of_adornment",
	baseObject = "spirit_mirror_pendant",
	uiName = "Medallion of Adornment",
	slot = "Neck",
}

cloneObject {
	name = "eob_ring2_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2",
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_sustenance_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_sustenance",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Sustenance",
}

cloneObject {
	name = "eob_long_sword_night_stalker_u",  -- 'Night Stalker'
	baseObject = "long_sword",
	uiName = "'Night Stalker'",
}

cloneObject {
	name = "eob_long_sword_night_stalker",
	baseObject = "long_sword",
	uiName = "'Night Stalker'",
}

cloneObject {
	name = "eob_cleric_scroll_hold_person_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_hold_person",
	baseObject = "scroll",
	uiName = "Scroll of Hold Person",
}

cloneObject {
	name = "eob_rock_glowing_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_glowing",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_key_ruby_u",  -- Ruby Key
	baseObject = "brass_key",
	uiName = "Ruby Key",
}

cloneObject {
	name = "eob_key_ruby",
	baseObject = "brass_key",
	uiName = "Ruby Key",
}

cloneObject {
	name = "eob_mage_scroll_invisibility 10'_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_invisibility 10'",
	baseObject = "scroll",
	uiName = "Scroll of Invisibility 10'",
}

cloneObject {
	name = "eob_bow_u",  -- Drow Bow
	baseObject = "short_bow",
	uiName = "Drow Bow",
}

cloneObject {
	name = "eob_bow",
	baseObject = "short_bow",
	uiName = "Drow Bow",
}

cloneObject {
	name = "eob_key_drow_u",  -- Drow Key
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_key_drow",
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil",
	baseObject = "scroll",
	uiName = "Scroll of Protect-Evil",
}

cloneObject {
	name = "eob_leather_boots_u",  -- Drow Boots
	baseObject = "leather_boots",
	uiName = "Drow Boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Drow Boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead",
	baseObject = "scroll",
	uiName = "Scroll of Raise Dead",
}

cloneObject {
	name = "eob_key_jeweled_u",  -- Jeweled Key
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_key_jeweled",
	baseObject = "brass_key",
	uiName = "Jeweled Key",
}

cloneObject {
	name = "eob_mage_scroll_shield_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_shield",
	baseObject = "scroll",
	uiName = "Scroll of Shield",
}

cloneObject {
	name = "eob_wand_lightning_bolt_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_lightning_bolt_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Lightning Bolt",
	charges = 10,
}

cloneObject {
	name = "eob_plate_mail_cursed3_u",  -- Plate Mail of Great Beauty
	baseObject = "plate_cuirass",
	uiName = "Plate Mail of Great Beauty",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_plate_mail_cursed3",
	baseObject = "plate_cuirass",
	uiName = "Plate Mail of Great Beauty",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_flail_u",  -- Flail
	baseObject = "flail",
	uiName = "Flail",
}

cloneObject {
	name = "eob_flail",
	baseObject = "flail",
	uiName = "Flail",
}

cloneObject {
	name = "eob_robe_u",  -- Robe
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_robe",
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_mace_u",  -- Scepter of Kingly Might
	baseObject = "knoffer",
	uiName = "Scepter of Kingly Might",
}

cloneObject {
	name = "eob_mace",
	baseObject = "knoffer",
	uiName = "Scepter of Kingly Might",
}

cloneObject {
	name = "eob_mage_scroll_ice_storm_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_ice_storm",
	baseObject = "scroll",
	uiName = "Scroll of Ice Storm",
}

cloneObject {
	name = "eob_lock_picks_u",  -- Lock picks
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_lock_picks",
	baseObject = "machine_part_south",
	uiName = "Lock picks",
}

cloneObject {
	name = "eob_gem_red_u",  -- Gem
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_gem_red",
	baseObject = "blue_gem",
	uiName = "Gem",
}

cloneObject {
	name = "eob_mage_scroll_vampiric_touch_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_vampiric_touch",
	baseObject = "scroll",
	uiName = "Scroll of Vampiric Touch",
}

---------------
--- Level 9 ---
---------------

cloneObject {
	name = "eob_key_drow_u",  -- Drow Key
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_key_drow",
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_cleric_scroll_detect_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_detect_magic",
	baseObject = "scroll",
	uiName = "Scroll of Detect Magic",
}

cloneObject {
	name = "eob_potion_poison_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_poison",
	baseObject = "potion_healing",
	uiName = "Potion of Poison",
}

cloneObject {
	name = "eob_mage_scroll_stone_skin_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_stone_skin",
	baseObject = "scroll",
	uiName = "Scroll of Stone Skin",
}

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_cleric_scroll_dispel_magic_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_dispel_magic",
	baseObject = "scroll",
	uiName = "Scroll of Dispel Magic",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Serious Wounds",
}

cloneObject {
	name = "eob_mage_scroll_invisibility_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_invisibility",
	baseObject = "scroll",
	uiName = "Scroll of Invisibility",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade",
	baseObject = "scroll",
	uiName = "Scroll of Flame Blade",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil10_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_protect_evil10",
	baseObject = "scroll",
	uiName = "Scroll of Protect-Evil 10'",
}

cloneObject {
	name = "eob_mage_scroll_armor_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_armor",
	baseObject = "scroll",
	uiName = "Scroll of Armor",
}

cloneObject {
	name = "eob_shield_drow_u",  -- Drow Shield
	baseObject = "round_shield",
	uiName = "Drow Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield_drow",
	baseObject = "round_shield",
	uiName = "Drow Drow Shield",
	protection = 2,
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead",
	baseObject = "scroll",
	uiName = "Scroll of Raise Dead",
}

cloneObject {
	name = "eob_leather_boots_u",  -- Drow Boots
	baseObject = "leather_boots",
	uiName = "Drow Boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Drow Boots",
	slot = "Feet",
}

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_spear_u",  -- Spear
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_spear",
	baseObject = "legionary_spear",
	uiName = "Spear",
}

cloneObject {
	name = "eob_wand_fireball_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_fireball_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Fireball",
	charges = 10,
}

cloneObject {
	name = "eob_chain_mail_u",  -- Chainmail
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_chain_mail",
	baseObject = "ring_mail",
	uiName = "Chainmail",
	slot = "Torso",
	protection = 10,
}

cloneObject {
	name = "eob_bones_human_beohram_u",  -- Human Bones
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_bones_human_beohram",
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_plate_mail_u",  -- Plate Mail
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_plate_mail",
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_shield_u",  -- Shield
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Shield",
	protection = 2,
}

cloneObject {
	name = "eob_long_sword_severious_u",  -- 'Severious'
	baseObject = "long_sword",
	uiName = "'Severious'",
}

cloneObject {
	name = "eob_long_sword_severious",
	baseObject = "long_sword",
	uiName = "'Severious'",
}

cloneObject {
	name = "eob_dwarven_helmet_u",  -- Helmet
	baseObject = "full_helmet",
	uiName = "Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_dwarven_helmet",
	baseObject = "full_helmet",
	uiName = "Helmet",
	slot = "Head",
	protection = 2,
}

cloneObject {
	name = "eob_holy_symbol_u",  -- Paladin Holy Symbol
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}

cloneObject {
	name = "eob_holy_symbol",
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}

cloneObject {
	name = "eob_orb_of_power_u",  -- Orb of Power
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_orb_of_power",
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_dart_plus4_u",  -- Adamantite Dart
	baseObject = "shuriken",
	uiName = "Adamantite Dart",
}

cloneObject {
	name = "eob_dart_plus4",
	baseObject = "shuriken",
	uiName = "Adamantite Dart +4",
}

---------------
--- Level 10 ---
---------------

cloneObject {
	name = "eob_plate_mail_u",  -- Plate Mail
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_plate_mail",
	baseObject = "plate_cuirass",
	uiName = "Plate Mail",
	slot = "Torso",
	protection = 14,
}

cloneObject {
	name = "eob_potion_poison_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_poison",
	baseObject = "potion_healing",
	uiName = "Potion of Poison",
}

cloneObject {
	name = "eob_wand_cone_of_cold_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_cone_of_cold_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Cone of Cold",
	charges = 10,
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_flame_blade",
	baseObject = "scroll",
	uiName = "Scroll of Flame Blade",
}

cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Critical Wounds",
}

cloneObject {
	name = "eob_wand_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
}

cloneObject {
	name = "eob_wand",
	baseObject = "whitewood_wand",
	uiName = "Wand",
}

cloneObject {
	name = "eob_arrow_u",  -- Arrow
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject {
	name = "eob_key_skull_u",  -- Skull Key
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_key_skull",
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_ring2_feather_fall_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2_feather_fall",
	baseObject = "bracelet_tirin",
	uiName = "Ring of Feather Fall",
}

cloneObject {
	name = "eob_potion_giant_strength_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_giant_strength",
	baseObject = "potion_healing",
	uiName = "Potion of Giant Strength",
}

cloneObject {
	name = "eob_cleric_scroll_remove_paralysis_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_remove_paralysis",
	baseObject = "scroll",
	uiName = "Scroll of Remove Paralysis",
}

cloneObject {
	name = "eob_cleric_scroll_neutral_poison_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_neutral_poison",
	baseObject = "scroll",
	uiName = "Scroll of Neutral-Poison",
}

cloneObject {
	name = "eob_mage_scroll_cone_of_cold_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_cone_of_cold",
	baseObject = "scroll",
	uiName = "Scroll of Cone of Cold",
}

cloneObject {
	name = "eob_bones_elf_tyrra_u",  -- Human Bones
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_bones_elf_tyrra",
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

---------------
--- Level 11 ---
---------------

cloneObject {
	name = "eob_dwarven_potion_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_dwarven_potion_healing",
	baseObject = "potion_healing",
	uiName = "Dwarven Healing Potion",
}

cloneObject {
	name = "eob_stone_holy_symbol_u",  -- Stone Holy Symbol
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
}

cloneObject {
	name = "eob_stone_holy_symbol",
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
}

cloneObject {
	name = "eob_wand_lightning_bolt_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_lightning_bolt_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Lightning Bolt",
	charges = 10,
}

cloneObject {
	name = "eob_medallion_luck_stone_u",  -- Medallion
	baseObject = "frostbite_necklace",
	uiName = "Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_luck_stone",
	baseObject = "frostbite_necklace",
	uiName = "Luck Stone Medallion",
	slot = "Neck",
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_raise_dead",
	baseObject = "scroll",
	uiName = "Scroll of Raise Dead",
}

cloneObject {
	name = "eob_stone_orb_u",  -- Stone Orb
	baseObject = "rock",
	uiName = "Stone Orb",
}

cloneObject {
	name = "eob_stone_orb",
	baseObject = "rock",
	uiName = "Stone Orb",
}

cloneObject {
	name = "eob_key_drow_u",  -- Drow Key
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_key_drow",
	baseObject = "brass_key",
	uiName = "Drow Key",
}

cloneObject {
	name = "eob_orb_of_power__from_level11_u",  -- Orb of Power
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_orb_of_power__from_level11",
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_rock_mossy_u",  -- Rock
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_mossy",
	baseObject = "rock",
	uiName = "Mossy Rock",
}

cloneObject {
	name = "eob_long_sword_slasher_u",  -- 'Slasher'
	baseObject = "long_sword",
	uiName = "'Slasher'",
}

cloneObject {
	name = "eob_long_sword_slasher",
	baseObject = "long_sword",
	uiName = "'Slasher'",
}

cloneObject {
	name = "eob_banded_armor_plus3_u",  -- Banded Armor
	baseObject = "ring_mail",
	uiName = "Banded Armor",
	slot = "Torso",
	protection = 12,
}

cloneObject {
	name = "eob_banded_armor_plus3",
	baseObject = "ring_mail",
	uiName = "Banded Armor",
	slot = "Torso",
	protection = 12,
}

cloneObject {
	name = "eob_ring2_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2",
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_mage_scroll_hold_monster_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_mage_scroll_hold_monster",
	baseObject = "scroll",
	uiName = "Scroll of Hold Monster",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
}

cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Serious Wounds",
}

cloneObject {
	name = "eob_robe_protection5_u",  -- Robe
	baseObject = "peasant_tunic",
	uiName = "Robe",
	slot = "Torso",
}

cloneObject {
	name = "eob_robe_protection5",
	baseObject = "peasant_tunic",
	uiName = "Robe of Defense",
	slot = "Torso",
}

cloneObject {
	name = "eob_dagger_flicka_u",  -- 'Flicka'
	baseObject = "dagger",
	uiName = "'Flicka'",
}

cloneObject {
	name = "eob_dagger_flicka",
	baseObject = "dagger",
	uiName = "'Flicka' of 'Flicka'",
}

cloneObject {
	name = "eob_bones_human_kirath_u",  -- Human Bones
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_bones_human_kirath",
	baseObject = "remains_of_toorum",
	uiName = "Human Bones",
}

cloneObject {
	name = "eob_ring_protection2_u",  -- Ring
	baseObject = "hardstone_bracelet",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring_protection2",
	baseObject = "hardstone_bracelet",
	uiName = "Ring of Protection +2",
}

cloneObject {
	name = "eob_bracers_defense2_u",  -- Bracers
	baseObject = "bracelet_tirin",
	uiName = "Bracers",
	slot = "Bracers",
}

cloneObject {
	name = "eob_bracers_defense2",
	baseObject = "bracelet_tirin",
	uiName = "Bracers of Defense",
	slot = "Bracers",
}

cloneObject {
	name = "eob_spell_book_u",  -- Spell Book
	baseObject = "tome_wisdom",
	uiName = "Spell Book",
}

cloneObject {
	name = "eob_spell_book",
	baseObject = "tome_wisdom",
	uiName = "Spell Book",
}

---------------
--- Level 12 ---
---------------

cloneObject {
	name = "eob_potion_extra_healing_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_extra_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
}

cloneObject {
	name = "eob_ring2_u",  -- Ring
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_ring2",
	baseObject = "bracelet_tirin",
	uiName = "Ring",
}

cloneObject {
	name = "eob_medallion_of_adornment_u",  -- Necklace
	baseObject = "spirit_mirror_pendant",
	uiName = "Necklace",
	slot = "Neck",
}

cloneObject {
	name = "eob_medallion_of_adornment",
	baseObject = "spirit_mirror_pendant",
	uiName = "Necklace",
	slot = "Neck",
}

cloneObject {
	name = "eob_wand_fireball_10_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 10,
}

cloneObject {
	name = "eob_wand_fireball_10",
	baseObject = "whitewood_wand",
	uiName = "Wand of Fireballs",
	charges = 10,
}

cloneObject {
	name = "eob_orb_of_power_u",  -- Orb of Power
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_orb_of_power",
	baseObject = "magic_orb",
	uiName = "Orb of Power",
}

cloneObject {
	name = "eob_potion_speed_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_speed",
	baseObject = "potion_healing",
	uiName = "Potion of Speed",
}

cloneObject {
	name = "eob_rations_iron_u",  -- Iron Rations
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_rations_iron",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
}

cloneObject {
	name = "eob_key_skull_u",  -- Skull Key
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_key_skull",
	baseObject = "brass_key",
	uiName = "Skull Key",
}

cloneObject {
	name = "eob_potion_invisibility_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_invisibility",
	baseObject = "potion_healing",
	uiName = "Potion of Invisibility",
}

cloneObject {
	name = "eob_potion_vitality_u",  -- Potion
	baseObject = "potion_healing",
	uiName = "Potion",
}

cloneObject {
	name = "eob_potion_vitality",
	baseObject = "potion_healing",
	uiName = "Potion of Vitality",
}

cloneObject {
	name = "eob_wand_magic_missile_20_u",  -- Wand
	baseObject = "whitewood_wand",
	uiName = "Wand",
	charges = 20,
}

cloneObject {
	name = "eob_wand_magic_missile_20",
	baseObject = "whitewood_wand",
	uiName = "Wand of Magic Missile",
	charges = 20,
}

cloneObject {
	name = "eob_stone_scepter_u",  -- Stone Scepter
	baseObject = "rock",
	uiName = "Stone Scepter",
}

cloneObject {
	name = "eob_stone_scepter",
	baseObject = "rock",
	uiName = "Stone Scepter",
}

cloneObject {
	name = "eob_stone_dagger_u",  -- Stone dagger
	baseObject = "rock",
	uiName = "Stone dagger",
}

cloneObject {
	name = "eob_stone_dagger",
	baseObject = "rock",
	uiName = "Stone dagger",
}

cloneObject {
	name = "eob_stone_medallion_u",  -- Stone Medallion
	baseObject = "rock",
	uiName = "Stone Medallion",
}

cloneObject {
	name = "eob_stone_medallion",
	baseObject = "rock",
	uiName = "Stone Medallion",
}

cloneObject {
	name = "eob_stone_necklace_u",  -- Stone Necklace
	baseObject = "rock",
	uiName = "Stone Necklace",
}

cloneObject {
	name = "eob_stone_necklace",
	baseObject = "rock",
	uiName = "Stone Necklace",
}

cloneObject {
	name = "eob_stone_scepter_u",  -- Stone Ring
	baseObject = "rock",
	uiName = "Stone Ring",
}

cloneObject {
	name = "eob_stone_scepter",
	baseObject = "rock",
	uiName = "Stone Ring",
}

cloneObject {
	name = "eob_stone_holy_symbol_u",  -- Stone Holy Symbol
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
}

cloneObject {
	name = "eob_stone_holy_symbol",
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
}

cloneObject {
	name = "eob_stone_orb_u",  -- Stone Orb
	baseObject = "rock",
	uiName = "Stone Orb",
}

cloneObject {
	name = "eob_stone_orb",
	baseObject = "rock",
	uiName = "Stone Orb",
}

