-- This file has been generated by Dungeon Editor beta-1.2.6

-- Eye of the Beholder Items --

-- ==================================== --
-- ============= LEVEL 01 ============= --
-- ==================================== --

cloneObject{
	name = "eob_rock",
	baseObject = "rock",
	uiName = "Rock",
}

cloneObject {
	name = "eob_rock_glowing",
	baseObject = "eob_rock",
	uiName = "Igneous Rock",
}

cloneObject{
	name = "eob_note_commission",
	baseObject = "note",
	uiName = "Letter",
	description = "Commission and Letter of Marque",
}

cloneObject{
	name = "eob_rations",
	baseObject = "pitroot_bread",
	uiName = "Rations",
	nutritionValue = 270,
	weight = 0.5,
}
cloneObject{
	name = "eob_iron_rations",
	baseObject = "pitroot_bread",
	uiName = "Iron Rations",
	nutritionValue = 650,
	weight = 0.9,
}

cloneObject{
	name = "eob_lock_picks",
	baseObject = "machine_part_south",
	uiName = "Lock Picks",
	description = "Set of a special Lock Picks",
	gfxIndex = 1,
    gfxAtlas = "mod_assets/textures/gui/items_3.tga",
	model = "mod_assets/models/items/lockpick/eob_lockpicks.fbx",
	key = true,
	weight = 0.5,
}

cloneObject{
	name = "eob_remains_of_tod_uphill",
	baseObject = "remains_of_toorum",
	uiName = "Halfling Bones",
	description = "Remains of Tod Uphill, a brave halfling thief.",
}

cloneObject{
	name = "eob_short_sword",
	baseObject = "machete",
	uiName = "Short Sword",
}

cloneObject{
	name = "eob_dagger",
	baseObject = "dagger",
	uiName = "Dagger",
	description = "Throwing Dagger",
	skill = "throwing_weapons",
	key = true,
	throwingWeapon = true,
	attackMethod = "throwAttack",
	attackSound = "swipe",
	impactSound = "impact_blade",
	stackable = true,
	sharpProjectile = true,
	projectileRotationSpeed = -15,
	--projectileRotationX = 90,
	--projectileRotationY = 90,
    projectileRotationZ = 90,
	weight = 0.3,
}

defineObject{
	name = "eob_dagger_guinsoo",
	class = "Item",
	uiName = "Guinsoo",
	model = "assets/models/items/assassin_dagger.fbx",
	description = "Powerfull throwing dagger called Guinsoo.",
	skill = "throwing_weapons",
	throwingWeapon = true,
	damageType = "physical",
	gfxIndex = 142,
	attackPower = 11,
	accuracy = 8,
	coolDownTime = 2.8,
	attackMethod = "throwAttack",
	attackSound = "swipe_light",
	impactSound = "impact_blade",
	sharpProjectile = true,
	projectileRotationSpeed = -10,
	-- projectileRotationX = 90,
	-- projectileRotationY = 90,
	projectileRotationZ = 90,
	weight = 0.8,
}

cloneObject{
	name = "eob_scroll_detect_magic",
	baseObject = "scroll",
	uiName = "Scroll of Detect Magic",
	description = "Mage scroll of Detect Magic.",
}
--[[
cloneObject{
	name = "eob_scroll_armor",
	baseObject = "scroll_armor",
	uiName = "Scroll of Armor",
	description = "Mage scroll of Armor.",
}]]
cloneObject{
	name = "eob_scroll_bless",
	baseObject = "scroll",
	uiName = "Scroll of Bless",
	description = "Cleric scroll of Bless.",
}

cloneObject{
	name = "eob_dart_2",
	baseObject = "shuriken",
	uiName = "Dart +2",
}

cloneObject{
	name = "eob_arrow",
	baseObject = "arrow",
	uiName = "Arrow",
}

cloneObject{
	name = "eob_shield",
	baseObject = "round_shield",
	uiName = "Shield",
}

-- ==================================== --
-- ============= LEVEL 02 ============= --
-- ==================================== --

cloneObject{
	name = "eob_silver_key",
	baseObject = "round_key",
	uiName = "Silver Key",
	description = "Silver Key.",
}
cloneObject{
	name = "eob_gold_key",
	baseObject = "gold_key",
	uiName = "Gold Key",
	description = "Gold Key.",
}
--[[
cloneObject{
	name = "eob_scroll_shield",
	baseObject = "scroll_shield",
	uiName = "Scroll of Shield",
	description = "Mage scroll of Shield.",
}
cloneObject{
	name = "eob_scroll_invisibility",
	baseObject = "scroll_invisibility",
	uiName = "Scroll of Invisibility",
	description = "Mage scroll of Invisibility.",
}
]]

cloneObject{
	name = "eob_sling",
	baseObject = "sling",
	uiName = "Sling",
}

cloneObject{
	name = "eob_bow",
	baseObject = "short_bow",
	uiName = "Bow",
}

cloneObject{
	name = "eob_leather_boots",
	baseObject = "leather_boots",
	uiName = "Leather boots",
}

cloneObject{
	-- potion of healing with blue icon --
	name = "eob_potion_healing",
	baseObject = "potion_healing",
	uiName = "Potion of Healing",
	gfxIndex = 145,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		champion:modifyStat("health", 50)
		return true
	end,
	weight = 0.6,
}

cloneObject{
	-- potion of healing with blue icon --
	name = "eob_potion_healing_u",
	baseObject = "potion_healing",
	uiName = "Potion.",
	gfxIndex = 145,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		champion:modifyStat("health", 50)
		return true
	end,
	weight = 0.6,
}

cloneObject{
	-- potion of extra healing with blue icon --
	name = "eob_potion_healing_extra",
	baseObject = "potion_healing",
	uiName = "Potion of Extra Healing",
	gfxIndex = 145,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		champion:modifyStat("health", 100)
		return true
	end,
	weight = 0.9,
}

cloneObject{
	-- potion of extra healing with blue icon --
	name = "eob_potion_healing_extra_u",
	baseObject = "potion_healing",
	uiName = "Potion.",
	gfxIndex = 145,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		champion:modifyStat("health", 100)
		return true
	end,
	weight = 0.9,
}

cloneObject{
	-- potion of extra healing with green icon --
	name = "eob_potion_vitality",
	baseObject = "potion_healing",
	uiName = "Potion of Vitality",
	description = "Refresh a hungry character.",
	gfxIndex = 147,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		champion:modifyFood(1000)
		hudPrint(champion:getName().." feels no longer hungry!")
		return true
	end,
	weight = 0.6,
}

cloneObject{
	name = "eob_potion_giant_strength",
	baseObject = "potion_healing",
	uiName = "Potion of Giant Strength",
	description = "After drink, character obtain the Giant Strenght for 1 minute.",
	gfxIndex = 149,
	onUseItem = function(self, champion)
		playSound("consume_potion")
		local effect = "strBoost"
		local amount = 10
		local duration = 60
		local str_old = champion:getStatMax("strength")
		local isActive = scriptEffects.activateEffect( effect, champion:getOrdinal(), amount, duration)
		if isActive then
			champion:modifyStatCapacity("strength", amount)
			champion:modifyStat("strength", amount)
			fw.debugPrint("Actual Str="..str_old..", Max="..champion:getStatMax("strength"))
			hudPrint(champion:getName().." feels much stronger!")
		else
			hudPrint(champion:getName().." can use only one effect of Giant Strength at the same time!")
		end
		return true
	end,
	weight = 0.6,
}

-- ==================================== --
-- ============= LEVEL 03 ============= --
-- ==================================== --
cloneObject{
	name = "eob_mace",
	baseObject = "knoffer",
	uiName = "Mace",
}

cloneObject{
	name = "eob_scroll_cause_light_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cause Light Wnds",
	description = "Cleric Scroll of Cause Light Wounds.",
}

cloneObject{
	name = "eob_gem_red_u",
	baseObject = "red_gem",
	uiName = "Red Gem",
}
cloneObject{
	name = "eob_gem_red",
	baseObject = "red_gem",
	uiName = "Red Gem",
}
cloneObject{
	name = "eob_gem_blue_u",
	baseObject = "blue_gem",
	uiName = "Blue Gem",
}
cloneObject{
	name = "eob_gem_blue",
	baseObject = "blue_gem",
	uiName = "Blue Gem",
}

cloneObject{
	name = "eob_dagger_backstabber",
	baseObject = "eob_dagger_guinsoo",
	uiName = "Backstabber",
	model = "assets/models/items/assassin_dagger.fbx",
	description = "Throwing dagger called `Backstabber`.",
	attackPower = 12,
	accuracy = 9,
	coolDownTime = 2.5,
	weight = 0.8,
}

-- ==================================== --
-- ============= LEVEL 04 ============= --
-- ==================================== --
	
-- carlos
-- torches make fire damage 
-- spider webs are vulnerable to fire

-- original definition of torch
-- used with holders
	defineObject{
		name = "torch",
		class = "Item",
		uiName = "Torch",
		model = "assets/models/items/torch.fbx",
		gfxIndex = 130,
		torch = true,
		fuel = 1100,
		attackPower = 8,
		damageType ="fire",--added by carlos
		accuracy = 0,
		coolDownTime = 3,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe",
		impactSound = "impact_blunt",
		weight = 1.2,
	}


-- carlos
-- ==================================== --
-- ============= LEVEL 06 ============= --
-- ==================================== --
-- carlos

-- eggs are not stackable, also messes with special quest
cloneObject {
	name = "eob_egg_10",
	baseObject = "slime_bell",
	uiName = "Kenku Egg",
	stackable = false, 
}
-- carlos

-- ==================================== --
-- ============= LEVEL 08 ============= --
-- ==================================== --



-- ==================================== --
-- ====  New Items - Experimental ===== --
-- ==================================== --

cloneObject{
	name = "eob_note_map_level1",
	baseObject = "note",
	uiName = "Sewer System Map - Level 1",
}

-- ATTEMP ON CURSED ITEMS

-- Plate Mail of Great Beauty
-- version to be found in dungeon 
-- looks like a common armor without negative effects
-- on equip is replaced with cursed version with negative effects
cloneObject {
	name = "eob_plate_mail_cursed3_u_dummy",  
	baseObject = "plate_cuirass",
	uiName = "Plate Mail of Great Beauty",
	slot = "Torso",
	protection = 12,
	onEquipItem = function(champion, slot)
		-- call only if item is equiped on body, not just placed in inventory
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.switchEquip(champion, slot)
		end
	end
}

-- cursed version with negative effects
cloneObject {
	name = "eob_plate_mail_cursed3_u",  
	baseObject = "plate_cuirass",
	uiName = "Plate Mail of Great Beauty",
	slot = "Torso",
	protection = -3,
	onUnequipItem = function(champion, slot)
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
	end
}

-- identified version
-- still cannot be put off, until dispel magic is cast
cloneObject {
	name = "eob_plate_mail_cursed3",
	baseObject = "plate_cuirass",
	uiName = "Plate Mail of Great Beauty",
	slot = "Torso",
	protection = -3,
	onUnequipItem = function(champion, slot)
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
		end
	end
}


-- cursed longsword
cloneObject {
	name = "eob_long_sword_cursed2_u_dummy",
	baseObject = "long_sword",
	uiName = "Longsword",
	attackPower = 14,
	onEquipItem = function(champion, slot)
		-- call only if item is equiped on body, not just placed in inventory
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.switchEquip(champion, slot)
		end
	end
}
cloneObject {
	name = "eob_long_sword_cursed2_u",
	baseObject = "long_sword",
	uiName = "Longsword",
	attackPower = -1,
	onUnequipItem = function(champion, slot)
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
	end
}

cloneObject {
	name = "eob_long_sword_cursed2",
	baseObject = "long_sword",
	uiName = "Unlucky Longsword",
	description = "It is unbelievable how hard is not to miss with this sword.",
	attackPower = -1,
	onUnequipItem = function(champion, slot)
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
		end
	end
}

-- cursed axe
cloneObject {
	name = "eob_axe_cursed3_u_dummy", 
	baseObject = "hand_axe",
	uiName = "Axe",
	attackPower = 10,
	onEquipItem = function(champion, slot)
		-- call only if item is equiped on body, not just placed in inventory
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.switchEquip(champion, slot)
		end
	end
}

cloneObject {
	name = "eob_axe_cursed3_u", 
	baseObject = "hand_axe",
	uiName = "Axe",
	attackPower = -3,
	onUnequipItem = function(champion, slot)
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
	end
}

cloneObject {
	name = "eob_axe_cursed3",
	baseObject = "hand_axe",
	uiName = "Axe Cursed -3",
	attackPower = -3,
	onUnequipItem = function(champion, slot)
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
		end
	end
}


-- cursed sling
cloneObject {
	name = "eob_sling_cursed3_u_dummy", 
	baseObject = "sling",
	uiName = "Sling",
	attackPower = 5,
	onEquipItem = function(champion, slot)
		-- call only if item is equiped on body, not just placed in inventory
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.switchEquip(champion, slot)
		end
	end
}

cloneObject {
	name = "eob_sling_cursed3_u", 
	baseObject = "sling",
	uiName = "Sling",
	attackPower = -3,
	onUnequipItem = function(champion, slot)
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
	end
}

cloneObject {
	name = "eob_sling_cursed3",
	baseObject = "sling",
	uiName = "Sling Cursed -3",
	attackPower = -3,
	onUnequipItem = function(champion, slot)
		if slot > 0 and slot < 11 
		then
		--calls script by Diarmuid on level 1 29,7
		script_entity_equipStopper.stopUnequip(champion, slot)
		end
	end
}

-- carlos
-- + Wently's Notes defined in notes.lua + --
-- --------------------------------------- --
--	name = "wentlys_note",
--	baseObject = "note",
--	uiName = "Wently's note",
-- --------------------------------------- --



-- carlos 
-- Paladin Holy Symbol, green
cloneObject {
	name = "eob_holy_symbol_paladin_u",  
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}

cloneObject {
	name = "eob_holy_symbol_paladin",
	baseObject = "golden_chalice",
	uiName = "Paladin Holy Symbol",
}
-- Cleric Holy symbol, yellow
cloneObject {
	name = "eob_holy_symbol_cleric_u",  
	baseObject = "golden_chalice",
	uiName = "Cleric Holy symbol",
}

cloneObject {
	name = "eob_holy_symbol_cleric",
	baseObject = "golden_chalice",
	uiName = "Cleric Holy symbol",
}


-- attempt on wands fix
-- WANDS OF MAGIC MISSILE
defineObject{
	name = "eob_wand_magic_missile_3_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "spellcraft",
	requiredLevel = 1,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "magic_missile",
	wandPower = 25,
	charges = 3,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_magic_missile_20_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "spellcraft",
	requiredLevel = 1,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "magic_missile",
	wandPower = 25,
	charges = 20,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}


defineObject{
	name = "eob_wand_magic_missile_3",
	class = "Item",
	uiName = "Wand of Magic missile",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Wand of Magic missile.",
	skill = "spellcraft",
	requiredLevel = 1,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "magic_missile",
	wandPower = 25,
	charges = 3,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_magic_missile_20",
	class = "Item",
	uiName = "Wand of Magic missile",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Wand of Magic missile.",
	skill = "spellcraft",
	requiredLevel = 1,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "magic_missile",
	wandPower = 25,
	charges = 20,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}


-- WANDS OF FIREBALL
defineObject{
	name = "eob_wand_fireball_10_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "fire_magic",
	requiredLevel = 13,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "fireball",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_fireball_10",
	class = "Item",
	uiName = "Wand of Fireball",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand of Fireball",
	skill = "fire_magic",
	requiredLevel = 13,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "fireball",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}


-- WANDS OF LIGHTNING BOLT
defineObject{
	name = "eob_wand_lightning_bolt_10_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "air_magic",
	requiredLevel = 14,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "lightning_bolt",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_lightning_bolt_10",
	class = "Item",
	uiName = "Wand of Lightning bolt.",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand of Lightning bolt.",
	skill = "air_magic",
	requiredLevel = 14,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "lightning_bolt",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}


-- WAND OF CONE OF COLD
defineObject{
	name = "eob_wand_cone_of_cold_2_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "ice_magic",
	requiredLevel = 19,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "cone_of_cold",
	wandPower = 25,
	charges = 2,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_cone_of_cold_2",
	class = "Item",
	uiName = "Wand of Cone of Cold",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand of Cone of Cold.",
	skill = "ice_magic",
	requiredLevel = 19,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "cone_of_cold",
	wandPower = 25,
	charges = 2,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_cone_of_cold_10_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "ice_magic",
	requiredLevel = 19,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "cone_of_cold",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_cone_of_cold_10",
	class = "Item",
	uiName = "Wand of Cone of Cold",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand of Cone of Cold.",
	skill = "ice_magic",
	requiredLevel = 19,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "cone_of_cold",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}


-- WAND OF ICE STORM
-- cant tell why this one doesnt work
defineObject{
	name = "eob_wand_ice_storm_10_u",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand.",
	skill = "ice_magic",
	requiredLevel = 13,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "ice_storm",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

defineObject{
	name = "eob_wand_ice_storm_10",
	class = "Item",
	uiName = "Wand of Ice Storm",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand of Ice Storm.",
	skill = "ice_magic",
	requiredLevel = 13,
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "castWandSpell",
	spell = "ice_storm",
	wandPower = 25,
	charges = 10,
	emptyItem = "eob_wand_empty",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}

-- DISCHARGED WANDS
-- LOST ALL ITS POWER 

defineObject{
	name = "eob_wand_empty",
	class = "Item",
	uiName = "Wand",
	model = "assets/models/items/whitewood_wand.fbx",
	description = "Magic wand - now completely drained.",
	gfxIndex = 56,
	attackPower = 14,
	accuracy = 0,
	coolDownTime = 5,
	attackMethod = "meleeAttack",
	attackSwipe = "vertical",
	attackSound = "swipe",
	impactSound = "impact_blunt",
	weight = 1.7,
}



-- PORTAL STONE ITEMS

-- Stone dagger
cloneObject{
	name = "eob_stone_dagger",
	baseObject = "dagger",
	uiName = "Stone Dagger",
	gfxIndex = 0,
    	gfxAtlas = "mod_assets/textures/gui/items_3.tga",
	model = "mod_assets/models/items/stone_dagger.fbx",
	key = true,
	attackPower = 5,
	accuracy = 3,
	weight = 0.5,
	stackable = false,
	glitterEffect = "magic_glow_blue",
}
cloneObject{
	name = "eob_stone_dagger_u",
	baseObject = "dagger",
	uiName = "Stone Dagger",
	gfxIndex = 0,
    	gfxAtlas = "mod_assets/textures/gui/items_3.tga",
	model = "mod_assets/models/items/stone_dagger.fbx",
	key = true,
	attackPower = 5,
	accuracy = 3,
	weight = 0.5,
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

-- Stone Gem
cloneObject{
	name = "eob_stone_gem_u",
	baseObject = "blue_gem",
	uiName = "Stone Gem",
	glitterEffect = "magic_glow_blue",
	stackable = false,
}

cloneObject{
	name = "eob_stone_gem",
	baseObject = "blue_gem",
	uiName = "Stone Gem",
	glitterEffect = "magic_glow_blue",
	stackable = false,
}


-- Stone Scepter
cloneObject {
	name = "eob_stone_scepter_u",  
	baseObject = "rock",
	uiName = "Stone Scepter",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}
cloneObject {
	name = "eob_stone_scepter",
	baseObject = "rock",
	uiName = "Stone Scepter",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

 -- Stone Medallion
cloneObject {
	name = "eob_stone_medallion_u", 
	baseObject = "rock",
	uiName = "Stone Medallion",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

cloneObject {
	name = "eob_stone_medallion",
	baseObject = "rock",
	uiName = "Stone Medallion",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

-- Stone Necklace
cloneObject {
	name = "eob_stone_necklace_u",  
	baseObject = "rock",
	uiName = "Stone Necklace",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

cloneObject {
	name = "eob_stone_necklace",
	baseObject = "rock",
	uiName = "Stone Necklace",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

-- Stone Holy Symbol
cloneObject {
	name = "eob_stone_holy_symbol_u",  
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

cloneObject {
	name = "eob_stone_holy_symbol",
	baseObject = "rock",
	uiName = "Stone Holy Symbol",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

-- Stone Orb
cloneObject {
	name = "eob_stone_orb_u",  
	baseObject = "rock",
	uiName = "Stone Orb",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}

cloneObject {
	name = "eob_stone_orb",
	baseObject = "rock",
	uiName = "Stone Orb",
	stackable = false,
	glitterEffect = "magic_glow_blue",
}


-- cleric scrolls
-- d&d 2.0 1d8
cloneObject {
	name = "eob_cleric_scroll_cure_light_wnds_u",  
	baseObject = "scroll",
	uiName = "Scroll",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 5 * math.random(5,8) ) 
		return true
	end,
}
cloneObject {
	name = "eob_cleric_scroll_cure_light_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Light Wounds",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 5 * math.random(5,8) )
		return true
	end,
}
-- d&d 2.0 2d8+1
cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds_u", 
	baseObject = "scroll",
	uiName = "Scroll",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 10 * math.random(5,8) ) 
		return true
	end,
}
cloneObject {
	name = "eob_cleric_scroll_cure_serious_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Serious Wounds",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 10 * math.random(1,8) )
		return true
	end,
}

-- d&d 2.0 3d8+3
cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds_u",  -- Scroll
	baseObject = "scroll",
	uiName = "Scroll",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 15 * math.random(5,8) )
		return true
	end,
}

cloneObject {
	name = "eob_cleric_scroll_cure_critical_wnds",
	baseObject = "scroll",
	uiName = "Scroll of Cure Critical Wounds",
	onUseItem = function(self, champion)
		playSound("generic_spell")
		champion:modifyStat("health", 15 * math.random(1,8) )
		return true
	end,
}




defineObject{
	name = "cube",
	class = "Item",
	uiName = "Shuriken",
	model = "mod_assets/models/env/eob_dwarven_wall_cube.fbx",
	skill = "throwing_weapons",
	gfxIndex = 12,
	throwingWeapon = true,
	attackPower = 11,
	coolDownTime = 3.5,
	attackMethod = "throwAttack",
	attackSound = "swipe",
	impactSound = "impact_blade",
	stackable = true,
	sharpProjectile = true,
	projectileRotationSpeed = 0,
	projectileRotationX = 0,
	projectileRotationY = 0,
	weight = 100,
}
-- carlos
