-- This file has been generated by Dungeon Editor beta-1.2.6

-- Materials for Eye of the Beholder mod --

-- Transparent texture --
defineMaterial{
   name = "clear_wall",
   diffuseMap = "mod_assets/textures/env/clear_walls_dif.tga",
   doubleSided = false,
   lighting = true,
   alphaTest = true,
   blendMode = "Opaque",
   textureAddressMode = "Wrap",
   glossiness = 0,
   depthBias = 0,
}

-- Sewers Wall --
defineMaterial{
	name = "eob_sewers_wall",
	diffuseMap = "mod_assets/textures/env/eob_sewers_wall_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_wall_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_wall_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}

-- Sewers WallBrick - rune transport (illusion wall)
defineMaterial{
	name = "eob_sewers_wallbrick_rune_transport",
	diffuseMap = "mod_assets/textures/env/eob_sewers_wallbrick_rune_transport_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_wallbrick_rune_transport_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_wallbrick_rune_transport_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}
-- Sewers WallBrick - carving (dagger alcove)
defineMaterial{
	name = "eob_sewers_wallbrick_carving",
	diffuseMap = "mod_assets/textures/env/eob_sewers_wallbrick_carving_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_wallbrick_carving_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_wallbrick_carving_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}
-- Sewers WallBrick - R.A.T.S text and arrow
defineMaterial{
	name = "eob_sewers_wallbrick_rats",
	diffuseMap = "mod_assets/textures/env/eob_sewers_wallbrick_rats_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_wallbrick_rats_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_wallbrick_rats_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}

-- Texture for sewer wall with the slime pipe drainage --
defineMaterial{
	name = "eob_sewers_wall_pipe",
	diffuseMap = "mod_assets/textures/env/eob_sewers_wall_pipe_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_wall_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_wall_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}

-- Sewers wall decorations (pipe drainage) --
defineMaterial{
	name = "eob_sewers_decoration",
	diffuseMap = "mod_assets/textures/env/eob_sewers_decorations_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_decorations_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_decorations_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}
defineMaterial{
	name = "eob_sewers_glowing_red",
	diffuseMap = "mod_assets/textures/env/eob_sewers_decorations_dif.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

-- Sewers Floor --
defineMaterial{
	name = "eob_sewers_floor",
	diffuseMap = "mod_assets/textures/env/sewers_hd_floor_dif.tga",
	specularMap = "mod_assets/textures/env/sewers_hd_floor_spec.tga",
	normalMap = "mod_assets/textures/env/sewers_hd_floor_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 80,
	depthBias = 0,
}

-- Sewers Floor Pressure Plate --
defineMaterial{
	name = "sewers_pressure_plate",
	diffuseMap = "mod_assets/textures/env/sewers_hd_floor_pressure_plate_dif.tga",
	specularMap = "mod_assets/textures/env/sewers_hd_floor_pressure_plate_spec.tga",
	normalMap = "mod_assets/textures/env/sewers_hd_floor_pressure_plate_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
} 

-- Ceiling for Sewers
defineMaterial{
	name = "eob_sewers_ceiling",
	diffuseMap = "mod_assets/textures/env/eob_sewers_ceiling_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_ceiling_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_ceiling_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}

-- Wall text (5x) - short text, rune Entrance
defineMaterial{
	name = "eob_sewers_walltext01",
	diffuseMap = "mod_assets/textures/env/eob_sewers_walltext01_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_walltext01_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_walltext01_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}

-- Sewers Door Metal --
defineMaterial{
	name = "sewers_door",
	diffuseMap = "mod_assets/textures/env/eob_sewers_door_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_door_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_door_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}

-- Sewers Door Frame (Arch) --
defineMaterial{
	name = "eob_sewers_door_frame",
	diffuseMap = "mod_assets/textures/env/eob_sewers_door_frame_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_door_frame_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_door_frame_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
} 

-- Ladder -- 
defineMaterial{
	name = "eob_ladder",
	diffuseMap = "mod_assets/textures/env/eob_ladder_dif.tga",
	specularMap = "mod_assets/textures/env/eob_ladder_spec.tga",
	normalMap = "mod_assets/textures/env/eob_ladder_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

-- Sewers Wall Secret Button - Large -- 
defineMaterial{
	name = "eob_sewers_sbutton_large",
	diffuseMap = "mod_assets/textures/env/eob_sewers_sbutton_large_dif.tga",
	specularMap = "mod_assets/textures/env/eob_sewers_sbutton_large_spec.tga",
	normalMap = "mod_assets/textures/env/eob_sewers_sbutton_large_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 5,
	depthBias = 0,
}
-- Wall Button - BLUE -
defineMaterial{
	name = "eob_button_blue",
	diffuseMap = "mod_assets/textures/props/eob_button_blue_dif.tga",
	specularMap = "mod_assets/textures/props/eob_button_blue_spec.tga",
	normalMap = "mod_assets/textures/props/eob_button_blue_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}
-- Wall Button - RED -
defineMaterial{
	name = "eob_button_red",
	diffuseMap = "mod_assets/textures/props/eob_button_red_dif.tga",
	specularMap = "mod_assets/textures/props/eob_button_blue_spec.tga",
	normalMap = "mod_assets/textures/props/eob_button_blue_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

-- Item: Stone Dagger --
defineMaterial{
	name = "stone_dagger",
	diffuseMap = "mod_assets/textures/items/stone_dagger_dif.tga",
	specularMap = "mod_assets/textures/items/stone_dagger_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}


-- Experimental, testing...

defineMaterial{
	name = "snair",
	diffuseMap = "mod_assets/textures/monsters/snail_red_dif.tga",
	specularMap = "assets/textures/monsters/snail_spec.tga",
	normalMap = "assets/textures/monsters/snail_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 90,
	depthBias = 0,
} 
defineMaterial{
	name = "snair_shell",
	diffuseMap = "mod_assets/textures/monsters/snail_red_dif.tga",
	specularMap = "assets/textures/monsters/snail_spec.tga",
	normalMap = "assets/textures/monsters/snail_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

-- Slug by Wallasaurus
defineMaterial{
	name = "basic_slug_material",
	diffuseMap = "mod_assets/textures/monsters/slug_dif.tga",
	specularMap = "mod_assets/textures/monsters/slug_spec.tga",
	normalMap = "mod_assets/textures/monsters/slug_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 50,
	depthBias = 0,
}
-- Leech by Wallasaurus
defineMaterial{
	name = "leech_worm_mat",
	diffuseMap = "mod_assets/textures/monsters/leech_worm_diffuse.tga",
	specularMap = "mod_assets/textures/monsters/leech_worm_spec.tga",
	normalMap = "mod_assets/textures/monsters/leech_worm_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 25,
	depthBias = 0,
}

-- Giant breakable spider webs
-- by montagneyaya (http://grimrock.nexusmods.com/mods/120/)
defineMaterial{
	name = "giant_spider_web",
	diffuseMap = "mod_assets/textures/props/giant_spider_web_dif.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = false,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "giant_spider_web_broken",
	diffuseMap = "mod_assets/textures/props/giant_spider_web_broken_dif.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = false,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

-- Item: Lockpick --
-- by Gizmojunk (http://grimrock.nexusmods.com/mods/98/)
defineMaterial{
	name = "eob_lockpicks",
	diffuseMap = "mod_assets/models/items/lockpick/eob_lockpicks_d.tga",
	specularMap = "mod_assets/models/items/lockpick/eob_lockpicks_s.tga",
	normalMap = "mod_assets/models/items/lockpick/eob_lockpicks_n.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}