-- This file has been generated by Dungeon Editor beta-1.2.6

-- Eye of the Beholder Monsters --

-- ==================================== --
-- ============= LEVEL 01 ============= --
-- ==================================== --

cloneObject{
   name = "eob_kobold",
   baseObject = "snail",
   model = "mod_assets/models/monsters/snail_red.fbx",
   health = 60,
   exp = 60,
   lootDrop = { }
}

fw_defineObject{
	name = "slug",
	class = "Monster",
	model = "mod_assets/models/monsters/slug.fbx",
	meshName = "slug_mesh003",
	animations = {
		idle = "assets/animations/monsters/snail/snail_idle.fbx",
		moveForward = "assets/animations/monsters/snail/snail_walk.fbx",
		turnLeft = "assets/animations/monsters/snail/snail_turn_left.fbx",
		turnRight = "assets/animations/monsters/snail/snail_turn_right.fbx",
		attack = "assets/animations/monsters/snail/snail_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/snail/snail_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/snail/snail_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/snail/snail_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/snail/snail_get_hit_right.fbx",
		fall = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
	},
	moveSound = "snail_walk",
	attackSound = "snail_attack",
	hitSound = "snail_hit",
	dieSound = "snail_die",
	hitEffect = "hit_goo",
	capsuleHeight = 0.2,
	capsuleRadius = 0.7,
	health = 90,
	sight = 2.5,
	attackPower = 6,
	movementCoolDown = 4,
	coolDown = { 0.5, 4 },
	evasion = -10,
	noRecoilInterval = { 0.1, 0.5 },
	exp = 60,
	lootDrop = { 75, "snail_slice", 10, "snail_slice" },
	healthIncrement = 30,
	attackPowerIncrement = 3,
	brain = "Melee",
}
defineObject{
	name = "leech_worm",
	class = "Monster",
	model = "mod_assets/models/monsters/leech_worm.fbx",
	meshName = "leech_worm_mesh",
	animations = {
		idle = "assets/animations/monsters/snail/snail_idle.fbx",
		moveForward = "assets/animations/monsters/snail/snail_walk.fbx",
		turnLeft = "assets/animations/monsters/snail/snail_turn_left.fbx",
		turnRight = "assets/animations/monsters/snail/snail_turn_right.fbx",
		attack = "assets/animations/monsters/snail/snail_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/snail/snail_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/snail/snail_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/snail/snail_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/snail/snail_get_hit_right.fbx",
		fall = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
	},
	moveSound = "snail_walk",
	attackSound = "snail_attack",
	hitSound = "snail_hit",
	dieSound = "snail_die",
	hitEffect = "hit_goo",
	capsuleHeight = 0.2,
	capsuleRadius = 0.7,
	health = 90,
	sight = 2.5,
	attackPower = 6,
	movementCoolDown = 4,
	coolDown = { 0.5, 4 },
	evasion = -10,
	noRecoilInterval = { 0.1, 0.5 },
	exp = 60,
	lootDrop = { 75, "snail_slice", 10, "snail_slice" },
	healthIncrement = 30,
	attackPowerIncrement = 3,
	brain = "Melee",
}

cloneObject{
   name = "eob_leech",
   baseObject = "leech_worm",
   health = 70,
   exp = 70,
   lootDrop = { }
}

-- ==================================== --
-- ============= LEVEL 02 ============= --
-- ==================================== --

cloneObject{
   name = "eob_zombie",
   baseObject = "skeleton_warrior",
   health = 70,
   accuracy = 9,
   protection = 4,
   coolDown = { 1, 4 },
   exp = 80,
   lootDrop = { }
}

cloneObject{
   name = "eob_skeleton",
   baseObject = "leki_skeleton_warrior_axe",
   health = 90,
   attackPower = 9,
   accuracy = 10,
   protection = 5,
   coolDown = { 1, 4 },
   exp = 85,
   lootDrop = { 50, "hand_axe"}
}
defineObject{
	name = "eob_skeleton_g4",
	class = "MonsterGroup",
	monsterType = "eob_skeleton",
	count = 4,
}

-- ==================================== --
-- ============= LEVEL 03 ============= --
-- ==================================== --

cloneObject{
	name = "eob_kuotoa",
	baseObject = "ice_lizard",
	health = 150,
	exp = 125,
	attackPower = 14,
	protection = 5,
	evasion = 6,
	accuracy = 15,
	movementCoolDown = 3,
	coolDown = { 1, 4 },
	healthIncrement = 20,
	attackPowerIncrement = 5,
	lootDrop = { }
}

cloneObject{
	name = "eob_flind",
	baseObject = "warden",
	health = 160,
	exp = 160,
	attackPower = 16,
	protection = 6,
	evasion = 7,
	accuracy = 18,
	movementCoolDown = 2,
	coolDown = { 1, 4 },
	healthIncrement = 20,
	attackPowerIncrement = 10,
	lootDrop = { }
}

-- workarounds for EobConverter bugs --
cloneObject {
	name = "eob_drider2",
	baseObject = "eob_drider"
}

-- carlos
-- redefining all here, not to mess with monsters_EobConverter.lua file
cloneObject{
   name = "eob_kuotoa1_1_museum",
   baseObject = "eob_kuotoa1_1",
   --when you damange this type of monster
   --all the blockers eob_blocker_museum_xx will be removed
   --this type of monster should be only use in museum on level 3
   onDamage = function(self, damage, damageType)
		script_entity_museum.onAttack() -- lvl 3 on 10,18
	     end,
}

cloneObject{
   name = "eob_flind1_2_museum",
   baseObject = "eob_flind1_2",
   --when you damage this type of monster
   --all the blockers eob_blocker_museum_xx will be removed
   --this type of monster should be only use in museum on level 3
   onDamage = function(self, damage, damageType)
		script_entity_museum.onAttack() -- lvl 3 on 10,18
	     end,
}


cloneObject {
	name = "eob_dwarf",
	baseObject = "skeleton_warrior",
-- if you attack any of the dwarves in game
-- then remove the dwarven camp blockers and dwarven dialogs
   onDamage = function(self, damage, damageType)
		--counter_dwarf_camp_attacked:increment()
		script_entity_dwarven_camp_attacked.attackDwarves()
	     end
}

--carlos

-- ==================================== --
-- ============= LEVEL 05 ============= --
-- ==================================== --
-- carlos
-- redefining all here, not to mess with monsters_EobConverter.lua file
cloneObject {
	name = "eob_dwarf",
	baseObject = "skeleton_warrior",
-- if you attack any of the dwarves in game
-- then remove the dwarven camp blockers and dwarven dialogs
   onDamage = function(self, damage, damageType)
		script_entity_dwarven_camp_attacked.attackDwarves() -- lvl 5 on 17,10
	     end
}


-- the rest are here only to inherit the above onDamage hook
cloneObject {
	name = "eob_dwarf1_1",
	baseObject = "eob_dwarf",
	lootDrop = {50, "eob_dwarven_helmet_u", 100, "eob_rations_u"},


}

cloneObject {
	name = "eob_dwarf2_1",
	baseObject = "eob_dwarf",
	lootDrop = {50, "eob_dwarven_helmet_u", 100, "eob_rations_u"},
}

defineObject {
	name = "eob_dwarf2_1_group",
	class = "MonsterGroup",
	monsterType = "eob_dwarf2_1",
	count = 2,
}

cloneObject {
	name = "eob_dwarf1_2",
	baseObject = "eob_dwarf",
	lootDrop = {50, "eob_axe_u", 100, "eob_rations_u"},
}

cloneObject {
	name = "eob_dwarf4_1",
	baseObject = "eob_dwarf",
	lootDrop = {},
	onDie = function(monster)
		if findEntity("eob_dwarf4_1_c") == nil then
			spawn("counter", 5, 0, 0, 0, "eob_dwarf4_1_c")
		end
		if eob_dwarf4_1_c:getValue() % 4 < 1 then
			if math.random(0,99) < 50 then
				spawn("eob_axe_u", monster.level, monster.x, monster.y, monster.facing, "eob_axe_u_18_14_"..eob_dwarf4_1_c:getValue())
			end
			spawn("eob_rations_u", monster.level, monster.x, monster.y, monster.facing, "eob_rations_u_1"..eob_dwarf4_1_c:getValue())
		elseif eob_dwarf4_1_c:getValue() % 4 < 4 then
			if math.random(0,99) < 50 then
				spawn("eob_dwarven_helmet_u", monster.level, monster.x, monster.y, monster.facing, "eob_dwarven_helmet_u_18_14_"..eob_dwarf4_1_c:getValue())
			end
			spawn("eob_rations_u", monster.level, monster.x, monster.y, monster.facing, "eob_rations_u_2"..eob_dwarf4_1_c:getValue())
		end
		eob_dwarf4_1_c:increment()
	end,
}

defineObject {
	name = "eob_dwarf4_1_group",
	class = "MonsterGroup",
	monsterType = "eob_dwarf4_1",
	count = 4,
}

--carlos


-- ==================================== --
-- ============= LEVEL 07 ============= --
-- ==================================== --

-- carlos
-- redefining all here, not to mess with monsters_EobConverter.lua file
cloneObject {
	name = "eob_drowelf",
	baseObject = "uggardian",
   	onDamage = function(self, damage, damageType)
		   script_entity_drow_patrol.onAttack() --lvl 7 on 2,19
		   end,
}

cloneObject {
	name = "eob_drowelf1_1",
	baseObject = "eob_drowelf",
	lootDrop = {50, "eob_long_sword_sharp_u"},
   	onDamage = function(self, damage, damageType)
		   script_entity_drow_patrol.onAttack() --lvl 7 on 2,19
		   end,
}

cloneObject {
	name = "eob_drowelf2_1",
	baseObject = "eob_drowelf",
	lootDrop = {50, "eob_long_sword_sharp_u"},
   	onDamage = function(self, damage, damageType)
		   script_entity_drow_patrol.onAttack() --lvl 7 on 2,19
		   end,
}

defineObject {
	name = "eob_drowelf2_1_group",
	class = "MonsterGroup",
	monsterType = "eob_drowelf2_1",
	count = 2,
   	onDamage = function(self, damage, damageType)
		   script_entity_drow_patrol.onAttack() --lvl 7 on 2,19
		   end,
}
--carlos

-- ==================================== --
-- ============= LEVEL 10 ============= --
-- ==================================== --
-- carlos
-- mantis "statues" for level 10 special quest
cloneObject {
	name = "eob_mantis",
	baseObject = "ogre",
}

cloneObject {
	name = "eob_mantis_dagger_statue",
	baseObject = "eob_mantis",
	lootDrop = {50, "eob_dagger"},
   	onDamage = function(self, damage, damageType)
		script_entity_special_quest_10.removeBlockers()	
	     end
}

cloneObject {
	name = "eob_mantis_halbred_statue",
	baseObject = "eob_mantis",
	lootDrop = {50, "eob_halberd_u"},
   	onDamage = function(self, damage, damageType)
		script_entity_special_quest_10.removeBlockers()
	     end
}
--carlos
