-- This file has been generated by Dungeon Editor beta-1.2.6

-- Eye of the Beholder Monsters --

-- ==================================== --
-- ============= LEVEL 01 ============= --
-- ==================================== --

cloneObject{
   name = "eob_kobold",
   baseObject = "snail",
   model = "mod_assets/models/monsters/snail_red.fbx",
   health = 60,
   exp = 60,
   lootDrop = { }
}

fw_defineObject{
	name = "slug",
	class = "Monster",
	model = "mod_assets/models/monsters/slug.fbx",
	meshName = "slug_mesh003",
	animations = {
		idle = "assets/animations/monsters/snail/snail_idle.fbx",
		moveForward = "assets/animations/monsters/snail/snail_walk.fbx",
		turnLeft = "assets/animations/monsters/snail/snail_turn_left.fbx",
		turnRight = "assets/animations/monsters/snail/snail_turn_right.fbx",
		attack = "assets/animations/monsters/snail/snail_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/snail/snail_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/snail/snail_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/snail/snail_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/snail/snail_get_hit_right.fbx",
		fall = "assets/animations/monsters/snail/snail_get_hit_front_left.fbx",
	},
	moveSound = "snail_walk",
	attackSound = "snail_attack",
	hitSound = "snail_hit",
	dieSound = "snail_die",
	hitEffect = "hit_goo",
	capsuleHeight = 0.2,
	capsuleRadius = 0.7,
	health = 90,
	sight = 2.5,
	attackPower = 6,
	movementCoolDown = 4,
	coolDown = { 0.5, 4 },
	evasion = -10,
	noRecoilInterval = { 0.1, 0.5 },
	exp = 60,
	lootDrop = { 75, "snail_slice", 10, "snail_slice" },
	healthIncrement = 30,
	attackPowerIncrement = 3,
	brain = "Melee",
}

cloneObject{
   name = "eob_leech",
   baseObject = "slug",
   health = 70,
   exp = 70,
   lootDrop = { }
}

-- ==================================== --
-- ============= LEVEL 02 ============= --
-- ==================================== --

cloneObject{
   name = "eob_zombie",
   baseObject = "skeleton_warrior",
   health = 70,
   accuracy = 9,
   protection = 4,
   coolDown = { 1, 4 },
   exp = 80,
   lootDrop = { }
}

cloneObject{
   name = "eob_skeleton",
   baseObject = "skeleton_warrior",
   health = 90,
   attackPower = 9,
   accuracy = 10,
   protection = 5,
   coolDown = { 1, 4 },
   exp = 85,
   lootDrop = { 50, "hand_axe"}
}
defineObject{
	name = "eob_skeleton_g4",
	class = "MonsterGroup",
	monsterType = "eob_skeleton",
	count = 4,
}

-- ==================================== --
-- ============= LEVEL 03 ============= --
-- ==================================== --

cloneObject{
	name = "eob_kuotoa",
	baseObject = "ice_lizard",
	health = 150,
	exp = 125,
	attackPower = 14,
	protection = 5,
	evasion = 6,
	accuracy = 15,
	movementCoolDown = 3,
	coolDown = { 1, 4 },
	healthIncrement = 20,
	attackPowerIncrement = 5,
	lootDrop = { }
}

cloneObject{
	name = "eob_flind",
	baseObject = "warden",
	health = 160,
	exp = 160,
	attackPower = 16,
	protection = 6,
	evasion = 7,
	accuracy = 18,
	movementCoolDown = 2,
	coolDown = { 1, 4 },
	healthIncrement = 20,
	attackPowerIncrement = 10,
	lootDrop = { }
}

-- workarounds for EobConverter bugs --
cloneObject {
	name = "eob_drider2",
	baseObject = "eob_drider"
}
