-- This file has been generated by EobConverter v0.9.9

--=========--
--== All ==--
--=========--

-----------------
--- Blockages ---
-----------------

cloneObject {
	name = "eob_blocker",
	baseObject = "blocker",
}

-------------------
--- Teleporters ---
-------------------

cloneObject {
	name = "eob_teleporter",
	baseObject = "teleporter",
}

--============--
--== Sewers ==--
--============--

-------------
--- Doors ---
-------------

cloneObject {
	name = "eob_sewers_door_metal_one",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_sewers_door_portcullis_one",
	baseObject = "dungeon_door_portcullis",
}

cloneObject {
	name = "eob_sewers_door_metal",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_sewers_door_metal",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_sewers_door_metal",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_sewers_door_metal_stacked",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_sewers_door_portcullis",
	baseObject = "dungeon_door_portcullis",
}

cloneObject {
	name = "eob_sewers_door_portcullis_stacked",
	baseObject = "dungeon_door_portcullis",
}

cloneObject {
	name = "eob_sewers_portcullis_throwable",
	baseObject = "dungeon_ivy_1",
}

-------------
--- Floor ---
-------------

cloneObject {
	name = "eob_sewers_pit",
	baseObject = "dungeon_pit",
}

cloneObject {
	name = "eob_sewers_pressure_plate",
	baseObject = "dungeon_pressure_plate",
}

---------------
--- Ceiling ---
---------------

cloneObject {
	name = "eob_sewers_ceiling_shaft",
	baseObject = "dungeon_ceiling_shaft",
}

-------------
--- Walls ---
-------------

cloneObject {
	name = "eob_sewers_illusion_wall_rune",
	baseObject = "dungeon_secret_door",
}

cloneObject {
	name = "eob_sewers_illusion_wall_rune",
	baseObject = "dungeon_secret_door",
}

------------------
--- Wall Texts ---
------------------

cloneObject {
	name = "eob_sewers_wall_text_long",
	baseObject = "dungeon_wall_text_long",
}

cloneObject {
	name = "eob_sewers_wall_text_rats",
	baseObject = "dungeon_wall_text_long",
}

cloneObject {
	name = "eob_sewers_wall_text_rune1",
	baseObject = "dungeon_wall_text",
}

-------------------
--- Decorations ---
-------------------

cloneObject {
	name = "eob_sewers_wall_drainage",
	baseObject = "dungeon_wall_drainage",
}

cloneObject {
	name = "eob_sewers_wall_drainage_bent",
	baseObject = "dungeon_wall_drainage",
}

cloneObject {
	name = "eob_sewers_wall_drainage_bent",
	baseObject = "dungeon_wall_drainage",
}

cloneObject {
	name = "eob_sewers_wall_pipe",
	baseObject = "receptor",
}

------------------------
--- Stairs / Ladders ---
------------------------

cloneObject {
	name = "eob_sewers_ladder_up",
	baseObject = "lever",
}

cloneObject {
	name = "eob_sewers_ladder_down",
	baseObject = "lever",
}

---------------
--- Alcoves ---
---------------

cloneObject {
	name = "eob_sewers_alcove",
	baseObject = "dungeon_alcove",
}

-------------
--- Locks ---
-------------

cloneObject {
	name = "eob_sewers_lock_iron",
	baseObject = "lock",
}

cloneObject {
	name = "eob_sewers_lock_silver",
	baseObject = "lock_round",
}

cloneObject {
	name = "eob_sewers_lock_golden",
	baseObject = "lock_golden",
}

cloneObject {
	name = "eob_sewers_lock_eye",
	baseObject = "lock_round",
}

cloneObject {
	name = "eob_sewers_lock_gem",
	baseObject = "lock_gear",
}

cloneObject {
	name = "eob_sewers_alcove_dagger",
	baseObject = "dungeon_alcove",
}

------------------------
--- Buttons / Levers ---
------------------------

cloneObject {
	name = "eob_sewers_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_sewers_secret_button_large",
	baseObject = "dungeon_secret_button_large",
}

cloneObject {
	name = "eob_sewers_secret_button_small",
	baseObject = "dungeon_secret_button_small",
}

cloneObject {
	name = "eob_sewers_button",
	baseObject = "wall_button",
}

cloneObject {
	name = "eob_sewers_switch",
	baseObject = "lever",
}

-----------------
--- Blockages ---
-----------------

cloneObject {
	name = "eob_sewers_cave_in",
	baseObject = "dungeon_cave_in",
}

---------------
--- Portals ---
---------------

cloneObject {
	name = "eob_sewers_portal_inactive",
	baseObject = "temple_glass_wall_2",
}

--===========--
--== Ruins ==--
--===========--

-------------
--- Doors ---
-------------

cloneObject {
	name = "eob_ruins_door_stone_one",
	baseObject = "temple_door_metal",
}

cloneObject {
	name = "eob_ruins_door_stone",
	baseObject = "temple_door_metal",
}

cloneObject {
	name = "eob_ruins_door_stone",
	baseObject = "temple_door_metal",
}

cloneObject {
	name = "eob_ruins_door_stone_stacked",
	baseObject = "temple_door_metal",
	openVelocity = 0.3,
	closeVelocity = 3,
--	closeAcceleration = 1,
--	closeSound = "assets/samples/monsters/cube_break_free.wav",
}

cloneObject {
	name = "eob_ruins_net",
	baseObject = "temple_door_portcullis",
}

cloneObject {
	name = "eob_ruins_net_torn",
	baseObject = "temple_door_portcullis",
}

-------------
--- Floor ---
-------------

cloneObject {
	name = "eob_ruins_pit",
	baseObject = "temple_pit",
}

cloneObject {
	name = "eob_ruins_pressure_plate",
	baseObject = "temple_pressure_plate",
}

---------------
--- Ceiling ---
---------------

cloneObject {
	name = "eob_ruins_ceiling_shaft",
	baseObject = "temple_ceiling_shaft",
}

-------------
--- Walls ---
-------------

cloneObject {
	name = "eob_ruins_illusion_wall",
	baseObject = "temple_secret_door",
}

cloneObject {
	name = "eob_ruins_illusion_wall_statue",
	baseObject = "temple_secret_door",
}

cloneObject {
	name = "eob_ruins_illusion_wall_rune",
	baseObject = "temple_secret_door",
}

------------------
--- Wall Texts ---
------------------

cloneObject {
	name = "eob_ruins_wall_text",
	baseObject = "temple_wall_text_long",
}

-------------------
--- Decorations ---
-------------------

cloneObject {
	name = "eob_ruins_wall_small_statue",
	baseObject = "temple_mosaic_wall_1",
}

------------------------
--- Stairs / Ladders ---
------------------------

cloneObject {
	name = "eob_ruins_stairs_up",
	baseObject = "temple_stairs_up",
}

cloneObject {
	name = "eob_ruins_stairs_down",
	baseObject = "temple_stairs_down",
}

---------------
--- Alcoves ---
---------------

cloneObject {
	name = "eob_ruins_alcove",
	baseObject = "temple_alcove",
}

-------------
--- Locks ---
-------------

cloneObject {
	name = "eob_ruins_statue_lock",
	baseObject = "lock",
}

cloneObject {
	name = "eob_ruins_ornate_lock",
	baseObject = "lock_ornate",
}

------------------------
--- Buttons / Levers ---
------------------------

cloneObject {
	name = "eob_ruins_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_ruins_statue_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_ruins_chain_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_ruins_secret_button_tiny",
	baseObject = "temple_secret_button_tiny",
}

cloneObject {
	name = "eob_ruins_button",
	baseObject = "wall_button",
}

------------------------
--- Firing mechanism ---
------------------------

cloneObject {
	name = "eob_ruins_dart_firing_pad",
	baseObject = "daemon_head",
}

---------------
--- Portals ---
---------------

cloneObject {
	name = "eob_ruins_portal_necklace",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_ruins_portal_scepter",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_ruins_portal_amulet",
	baseObject = "temple_glass_wall_2",
}

--==========--
--== Drow ==--
--==========--

-------------
--- Doors ---
-------------

cloneObject {
	name = "eob_drow_door_one",
	baseObject = "prison_door_metal",
}

cloneObject {
	name = "eob_drow_door",
	baseObject = "prison_door_metal",
}

cloneObject {
	name = "eob_drow_door",
	baseObject = "prison_door_metal",
}

-------------
--- Walls ---
-------------

cloneObject {
	name = "eob_drow_wall",
	baseObject = "prison_secret_door",
}

cloneObject {
	name = "eob_drow_wall_illusion_with_spider",
	baseObject = "temple_secret_door",
}

cloneObject {
	name = "eob_drow_wall_illusion",
	baseObject = "prison_secret_door",
}
cloneObject {
	name = "eob_drow_wall_throwable",
	baseObject = "dungeon_ivy_1",
}


-------------
--- Floor ---
-------------

cloneObject {
	name = "eob_drow_pit",
	baseObject = "prison_pit",
}

cloneObject {
	name = "eob_drow_pressure_plate",
	baseObject = "prison_pressure_plate",
}

---------------
--- Ceiling ---
---------------

cloneObject {
	name = "eob_drow_ceiling_shaft",
	baseObject = "prison_ceiling_shaft",
}

------------------
--- Wall Texts ---
------------------

cloneObject {
	name = "eob_drow_wall_text",
	baseObject = "prison_wall_text_long",
}
--[[ commented by carlos, looks like duplicate
cloneObject {
	name = "eob_drow_wall_text",
	baseObject = "dungeon_wall_text_long",
}
]]

------------------------
--- Stairs / Ladders ---
------------------------

cloneObject {
	name = "eob_drow_stairs_up",
	baseObject = "prison_stairs_up",
}

cloneObject {
	name = "eob_drow_stairs_down",
	baseObject = "prison_stairs_down",
}

---------------
--- Alcoves ---
---------------

cloneObject {
	name = "eob_drow_alcove",
	baseObject = "prison_alcove",
}

-------------
--- Locks ---
-------------

cloneObject {
	name = "eob_drow_lock_gem",
	baseObject = "lock_prison",
}

cloneObject {
	name = "eob_drow_lock_spider",
	baseObject = "lock",
}

cloneObject {
	name = "eob_drow_lock_ornate",
	baseObject = "lock_ornate",
}

---------------
--- Buttons ---
---------------

cloneObject {
	name = "eob_drow_secret_button_tiny",
	baseObject = "prison_secret_button_small",
}

------------------------
--- Buttons / Levers ---
------------------------

cloneObject {
	name = "eob_drow_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_drow_button",
	baseObject = "wall_button",
}

------------------------
--- Firing mechanism ---
------------------------

cloneObject {
	name = "eob_drow_fireball_firing_pad",
	baseObject = "daemon_head",
}

cloneObject {
	name = "eob_drow_fireball_firing_pad",
	baseObject = "daemon_head",
}

cloneObject {
	name = "eob_drow_dart_firing_pad",
	baseObject = "daemon_head",
}

cloneObject {
	name = "eob_drow_dart_firing_pad",
	baseObject = "daemon_head",
}

cloneObject {
	name = "eob_drow_magic_missile_firing_pad",
	baseObject = "daemon_head",
}

---------------
--- Portals ---
---------------

cloneObject {
	name = "eob_drow_portal_cross",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_necklace",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_dagger",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_dagger",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_amulet",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_scepter",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_drow_portal_gem",
	baseObject = "temple_glass_wall_2",
}

--==========--
--== Hive ==--
--==========--

-------------
--- Doors ---
-------------

cloneObject {
	name = "eob_hive_door_one",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_hive_door",
	baseObject = "dungeon_door_metal",
}

cloneObject {
	name = "eob_hive_door",
	baseObject = "prison_door_metal",
}

-------------
--- Floor ---
-------------

cloneObject {
	name = "eob_hive_pit",
	baseObject = "dungeon_pit",
}

cloneObject {
	name = "eob_hive_pressure_plate",
	baseObject = "dungeon_pressure_plate",
}

---------------
--- Ceiling ---
---------------

cloneObject {
	name = "eob_hive_ceiling_shaft",
	baseObject = "dungeon_ceiling_shaft",
}

------------------
--- Wall Texts ---
------------------

cloneObject {
	name = "eob_hive_wall_text",
	baseObject = "dungeon_wall_text_long",
}

-------------------
--- Decorations ---
-------------------

cloneObject {
	name = "eob_hive_prison_manacles",
	baseObject = "prison_bench",
}

cloneObject {
	name = "eob_hive_wall_rift",
	baseObject = "dungeon_ivy_1",
}

cloneObject {
	name = "eob_hive_wall_star",
	baseObject = "daemon_head",
}

------------------------
--- Stairs / Ladders ---
------------------------

cloneObject {
	name = "eob_hive_stairs_up",
	baseObject = "dungeon_stairs_up",
}

cloneObject {
	name = "eob_hive_stairs_down",
	baseObject = "dungeon_stairs_down",
}

---------------
--- Alcoves ---
---------------

cloneObject {
	name = "eob_hive_alcove",
	baseObject = "dungeon_alcove",
}

-------------
--- Locks ---
-------------

cloneObject {
	name = "eob_hive_lock",
	baseObject = "lock",
}

------------------------
--- Buttons / Levers ---
------------------------

cloneObject {
	name = "eob_hive_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_hive_lever",
	baseObject = "lever",
}

cloneObject {
	name = "eob_hive_switch",
	baseObject = "lever",
}

cloneObject {
	name = "eob_hive_secret_button_small",
	baseObject = "dungeon_secret_button_small",
}

cloneObject {
	name = "eob_hive_secret_button_tiny",
	baseObject = "dungeon_secret_button_small",
}

cloneObject {
	name = "eob_hive_button",
	baseObject = "wall_button",
}

cloneObject {
	name = "eob_hive_button2",
	baseObject = "wall_button",
}

---------------
--- Portals ---
---------------

cloneObject {
	name = "eob_hive_portal_cross",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_hive_portal_orb",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_hive_portal_scepter",
	baseObject = "temple_glass_wall_2",
}

cloneObject {
	name = "eob_hive_portal_ring",
	baseObject = "temple_glass_wall_2",
}

--=============--
--== Sanctum ==--
--=============--

-------------
--- Doors ---
-------------

cloneObject {
	name = "eob_sanctum_door_one",
	baseObject = "temple_door_metal",
}

cloneObject {
	name = "eob_sanctum_door",
	baseObject = "temple_door_metal",
}

cloneObject {
	name = "eob_sanctum_door",
	baseObject = "temple_door_metal",
}

-------------
--- Floor ---
-------------

cloneObject {
	name = "eob_sanctum_pressure_plate",
	baseObject = "temple_pressure_plate",
}

cloneObject {
	name = "eob_sanctum_spike_trap",
	baseObject = "temple_floor_drainage",
}

-------------------
--- Decorations ---
-------------------

cloneObject {
	name = "eob_sanctum_pedestal",
	baseObject = "altar",
}

cloneObject {
	name = "eob_sanctum_pedestal_eye",
	baseObject = "altar",
}

cloneObject {
	name = "eob_sanctum_pedestal_eye",
	baseObject = "altar",
}

cloneObject {
	name = "eob_sanctum_wall_lamp",
	baseObject = "torch_holder",
}

cloneObject {
	name = "eob_sanctum_wall_lamp_smoke",
	baseObject = "torch_holder",
}

------------------
--- Wall Texts ---
------------------

cloneObject {
	name = "eob_sanctum_text",
	baseObject = "temple_wall_text_long",
}

---------------
--- Alcoves ---
---------------

cloneObject {
	name = "eob_sanctum_alcove",
	baseObject = "temple_alcove",
}

-------------
--- Locks ---
-------------

cloneObject {
	name = "eob_sanctum_skull_lock",
	baseObject = "lock",
}

------------------------
--- Buttons / Levers ---
------------------------

cloneObject {
	name = "eob_sanctum_button",
	baseObject = "wall_button",
}

cloneObject {
	name = "eob_sanctum_button2",
	baseObject = "wall_button",
}

cloneObject {
	name = "eob_sanctum_secret_button_small",
	baseObject = "temple_secret_button_small",
}

cloneObject {
	name = "eob_sanctum_secret_button_tiny",
	baseObject = "temple_secret_button_small",
}

------------------------
--- Firing mechanism ---
------------------------

cloneObject {
	name = "eob_sanctum_fireball_firing_pad",
	baseObject = "daemon_head",
}

---------------
--- Portals ---
---------------

cloneObject {
	name = "eob_sanctum_portal_orb",
	baseObject = "temple_glass_wall_2",
}

