-- This file has been generated by Dungeon Editor beta-1.2.6

-- Sounds for Eye of the Beholder remake --

defineSound{
   name = "rockfall_01",
   filename = "mod_assets/sounds/rockfall_01.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
   name = "ladder_steps2",
   filename = "mod_assets/sounds/ladder_steps_01.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
   name = "laugh_human_male_echo",
   filename = "mod_assets/sounds/laugh_human_male_echo_01.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
   name = "waterfall_loop",
   filename = "mod_assets/sounds/waterfall.wav",
   loop = true,
   volume = 1,
   minDistance = 1,
   maxDistance = 5,
}

defineSound{
   name = "portal_open",
   filename = "mod_assets/sounds/portal_open.wav",
   loop = false,
   volume = 10,
   minDistance = 1,
   maxDistance = 10,
}
