-- This file has been generated by Dungeon Editor beta-1.2.6

-- Eye of the Beholder custom WallSets --

defineWallSet{
	name = "sewers",
	randomFloorFacing = false,
	floors = {
		"mod_assets/models/env/eob_sewers_floor.fbx", 1,
	},
	
	walls = {
		"mod_assets/models/env/eob_sewers_wall.fbx", 20,
		"mod_assets/models/env/eob_sewers_wall01.fbx", 1,
	},
	
	pillars = {
		"mod_assets/models/env/eob_sewers_pillar.fbx", 1,
	},

	ceilings = {
		"mod_assets/models/env/eob_sewers_ceiling.fbx", 1,
	},
	
	ceilingShafts = {
		"mod_assets/models/env/sewers_ceiling_pit.fbx", 1,
	},

	floorDecorations = {
		"mod_assets/models/env/sewers_floor_rocks.fbx", 5,
		"mod_assets/models/env/sewers_floor_rocks.fbx", 1,
	},
	
	wallDecorations = {},
	
	pillarDecorations = {},
}